bb_max_len = 2
max_switch_targets = 2
max_bb_count = 2
max_bb_count_hard = 2
max_fn_count = 2
max_args_count = 2
var_dump_chance = 0.5
tuple_max_len = 2
array_max_len = 2
struct_max_fields = 2
adt_max_variants = 2
composite_count = 2
adt_count = 2

[backends.llvm]
type = "llvm"
toolchain = "nightly"
flags = ["-Zmir-opt-level=0"]

[backends.tuffy]
type = "tuffy"
path = "/tuffy/rustc_codegen_tuffy/target/release/librustc_codegen_tuffy.so"
flags = ["-Zmir-opt-level=0"]
