//! Generate Rust isel dispatch code from parsed JSON rules.

use std::collections::HashMap;
use std::fmt::Write;

use crate::schema::*;

/// Generate the complete `isel_gen.rs` source file.
pub fn generate(spec: &IselSpec) -> String {
    let mut out = String::new();
    writeln!(out, "// @generated by tuffy_isel_gen -- DO NOT EDIT").unwrap();
    writeln!(out).unwrap();

    for import in &spec.metadata.imports {
        writeln!(out, "{import}").unwrap();
    }
    writeln!(out, "use tuffy_ir::instruction::{{ICmpOp, Op}};").unwrap();
    writeln!(
        out,
        "use tuffy_ir::types::{{Annotation, IntAnnotation, IntSignedness}};"
    )
    .unwrap();
    writeln!(out, "use tuffy_ir::value::ValueRef;").unwrap();
    writeln!(out, "use tuffy_regalloc::VReg;").unwrap();
    writeln!(out).unwrap();

    // Generate per-rule helper functions.
    for rule in &spec.rules {
        generate_rule_fn(&mut out, rule, &spec.metadata);
    }

    // Generate the dispatch function.
    generate_dispatch(&mut out, &spec.rules);

    out
}

/// Map from register name to Rust variable name, tracking fresh allocations.
struct RegEnv {
    map: HashMap<String, String>,
    counter: u32,
}

impl RegEnv {
    fn new() -> Self {
        Self {
            map: HashMap::new(),
            counter: 0,
        }
    }

    fn resolve(
        &mut self,
        r: &RegRef,
        out: &mut String,
        metadata: &IselMetadata,
        ctx: &EmitContext<'_>,
    ) -> Result<String, String> {
        match r.kind {
            RegRefKind::Named => {
                // Named refs are function parameters — use the name directly.
                Ok(r.name.clone())
            }
            RegRefKind::Fresh => {
                if let Some(existing) = self.map.get(&r.name) {
                    return Ok(existing.clone());
                }
                let var = format!("v{}", self.counter);
                self.counter += 1;
                writeln!(out, "    let {var} = ctx.alloc.alloc();").unwrap();
                self.map.insert(r.name.clone(), var.clone());
                Ok(var)
            }
            RegRefKind::FreshFixed => {
                if let Some(existing) = self.map.get(&r.name) {
                    return Ok(existing.clone());
                }
                let reg_key = r.reg.as_deref().ok_or_else(|| {
                    ctx.error(
                        ctx.field_name,
                        "fresh_fixed register reference is missing explicit `reg`",
                    )
                })?;
                let preg = metadata.maps.fixed_regs.get(reg_key).ok_or_else(|| {
                    ctx.error(
                        ctx.field_name,
                        format!("missing metadata.maps.fixed_regs entry for key `{reg_key}`"),
                    )
                })?;
                let var = format!("v{}", self.counter);
                self.counter += 1;
                writeln!(out, "    let {var} = ctx.alloc.alloc_fixed({preg});").unwrap();
                self.map.insert(r.name.clone(), var.clone());
                Ok(var)
            }
        }
    }
}

/// Collect the named register parameters from a pattern.
fn pattern_params(pattern: &IrPattern) -> Vec<String> {
    match pattern {
        IrPattern::Binop { lhs, rhs, .. } => vec![lhs.reg.clone(), rhs.reg.clone()],
        IrPattern::Unop { val, .. } => vec![val.reg.clone()],
        IrPattern::Icmp { lhs, rhs } => vec![lhs.reg.clone(), rhs.reg.clone()],
    }
}

/// Check if a rule uses fromAnnotation for any OpSize.
fn needs_annotation_params(rule: &IselRule) -> Vec<String> {
    let mut regs = Vec::new();
    for inst in &rule.emit {
        for field in &inst.fields {
            if let EmitField::Size {
                value: OpSizeValue::FromAnnotation { reg, .. },
                ..
            } = field
                && !regs.contains(reg)
            {
                regs.push(reg.clone());
            }
        }
    }
    regs
}

/// Generate a per-rule function like `fn gen_add(...)`.
fn generate_rule_fn(out: &mut String, rule: &IselRule, metadata: &IselMetadata) {
    let params = pattern_params(&rule.pattern);
    let param_list: String = params
        .iter()
        .map(|p| format!("{p}: VReg"))
        .collect::<Vec<_>>()
        .join(", ");

    let ann_regs = needs_annotation_params(rule);
    let ann_params: String = ann_regs
        .iter()
        .map(|r| format!(", {r}_ann: Option<Annotation>"))
        .collect::<Vec<_>>()
        .join("");

    let extra_params = if rule.icmp_cc_from_op {
        ", cmp_op: ICmpOp, lhs_ann: Option<Annotation>"
    } else {
        &ann_params
    };

    writeln!(
        out,
        "fn gen_{name}(ctx: &mut super::IselCtx, vref: ValueRef, {param_list}{extra_params}) -> Option<()> {{",
        name = rule.name
    )
    .unwrap();

    // Build register environment with named params pre-populated.
    let mut env = RegEnv::new();
    for p in &params {
        env.map.insert(p.clone(), p.clone());
    }

    // Emit instructions.
    let mut inst_lines = String::new();
    for (inst_index, inst) in rule.emit.iter().enumerate() {
        emit_inst(&mut inst_lines, inst, &mut env, metadata, rule, inst_index)
            .unwrap_or_else(|e| panic!("{e}"));
    }
    out.push_str(&inst_lines);

    // Assign result.
    match &rule.result {
        ResultKind::Reg { name } => {
            let var = env.map.get(name).expect("result reg not found in env");
            writeln!(out, "    ctx.regs.assign(vref, {var});").unwrap();
        }
        ResultKind::CmpFlags => {
            writeln!(out, "    let int_ann = lhs_ann.and_then(|a| if let Annotation::Int(ia) = a {{ Some(ia) }} else {{ None }});").unwrap();
            writeln!(out, "    let cc = super::icmp_to_cc(cmp_op, int_ann);").unwrap();
            writeln!(out, "    ctx.cmps.set(vref, cc);").unwrap();
        }
        ResultKind::None => {}
    }

    writeln!(out, "    Some(())").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

/// Format a struct field assignment, using shorthand when variable name matches field name.
fn field(name: &str, var: &str) -> String {
    if name == var {
        name.to_string()
    } else {
        format!("{name}: {var}")
    }
}

struct EmitContext<'a> {
    rule_name: &'a str,
    inst_index: usize,
    field_name: &'a str,
}

impl<'a> EmitContext<'a> {
    fn error(&self, field_name: &str, msg: impl AsRef<str>) -> String {
        format!(
            "isel generation error [rule={}, inst={}, field={}]: {}",
            self.rule_name,
            self.inst_index,
            field_name,
            msg.as_ref()
        )
    }
}

fn map_lookup<'a>(
    map: &'a HashMap<String, String>,
    map_name: &'static str,
    key: &str,
    ctx: &EmitContext<'_>,
) -> Result<&'a str, String> {
    map.get(key).map(|v| v.as_str()).ok_or_else(|| {
        ctx.error(
            ctx.field_name,
            format!("missing {map_name} entry for key `{key}`"),
        )
    })
}

/// Emit a single MInst push statement.
fn emit_inst(
    out: &mut String,
    inst: &EmitInst,
    env: &mut RegEnv,
    metadata: &IselMetadata,
    rule: &IselRule,
    inst_index: usize,
) -> Result<(), String> {
    if inst.rust_ctor.trim().is_empty() {
        return Err(EmitContext {
            rule_name: &rule.name,
            inst_index,
            field_name: "rust_ctor",
        }
        .error("rust_ctor", "constructor must not be empty"));
    }

    // We need a separate buffer for alloc lines that must come before the push.
    let mut alloc_buf = String::new();
    let mut rendered_fields: Vec<String> = Vec::with_capacity(inst.fields.len());

    for emit_field in &inst.fields {
        match emit_field {
            EmitField::Reg { name, reg_ref } => {
                let ctx = EmitContext {
                    rule_name: &rule.name,
                    inst_index,
                    field_name: name,
                };
                let resolved = env.resolve(reg_ref, &mut alloc_buf, metadata, &ctx)?;
                rendered_fields.push(field(name, &resolved));
            }
            EmitField::Size { name, value } => {
                let ctx = EmitContext {
                    rule_name: &rule.name,
                    inst_index,
                    field_name: name,
                };
                match value {
                    OpSizeValue::Fixed(size_str) => {
                        let mapped =
                            map_lookup(&metadata.maps.size, "metadata.maps.size", size_str, &ctx)?;
                        rendered_fields.push(format!("{name}: {mapped}"));
                    }
                    OpSizeValue::FromAnnotation { kind, reg } => {
                        if kind != "from_annotation" {
                            return Err(
                                ctx.error(name, format!("unknown OpSizeValue kind: {kind}"))
                            );
                        }
                        let size_var = format!("size_{}", inst_index);
                        let ann_param = format!("{reg}_ann");
                        writeln!(&mut alloc_buf, "    let {size_var} = match {ann_param} {{")
                            .unwrap();
                        writeln!(
                            &mut alloc_buf,
                            "        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {{"
                        )
                        .unwrap();
                        writeln!(&mut alloc_buf, "            8 => OpSize::S8,").unwrap();
                        writeln!(&mut alloc_buf, "            16 => OpSize::S16,").unwrap();
                        writeln!(&mut alloc_buf, "            32 => OpSize::S32,").unwrap();
                        writeln!(&mut alloc_buf, "            _ => OpSize::S64,").unwrap();
                        writeln!(&mut alloc_buf, "        }},").unwrap();
                        writeln!(&mut alloc_buf, "        _ => OpSize::S64,").unwrap();
                        writeln!(&mut alloc_buf, "    }};").unwrap();
                        rendered_fields.push(format!("{name}: {size_var}"));
                    }
                }
            }
            EmitField::Cc { name, value } => {
                let ctx = EmitContext {
                    rule_name: &rule.name,
                    inst_index,
                    field_name: name,
                };
                let mapped = map_lookup(&metadata.maps.cc, "metadata.maps.cc", value, &ctx)?;
                rendered_fields.push(format!("{name}: {mapped}"));
            }
            EmitField::Literal { name, value } => {
                let _ctx = EmitContext {
                    rule_name: &rule.name,
                    inst_index,
                    field_name: name,
                };
                rendered_fields.push(format!("{name}: {value}"));
            }
        }
    }

    out.push_str(&alloc_buf);
    writeln!(
        out,
        "    ctx.out.push({} {{ {} }});",
        inst.rust_ctor,
        rendered_fields.join(", ")
    )
    .unwrap();

    Ok(())
}

/// Group rules by their IR op name for dispatch.
struct OpGroup<'a> {
    op_name: String,
    /// Rules for this op, with their annotation guards on the LHS operand.
    rules: Vec<(AnnGuard, &'a IselRule)>,
}

/// Generate the `try_select_generated` dispatch function.
fn generate_dispatch(out: &mut String, rules: &[IselRule]) {
    writeln!(out, "#[allow(unused_variables)]").unwrap();
    writeln!(out, "pub(super) fn try_select_generated(").unwrap();
    writeln!(out, "    ctx: &mut super::IselCtx,").unwrap();
    writeln!(out, "    vref: ValueRef,").unwrap();
    writeln!(out, "    op: &Op,").unwrap();
    writeln!(out, ") -> Option<()> {{").unwrap();
    writeln!(out, "    match op {{").unwrap();

    // Group rules by Op variant.
    let mut groups: Vec<OpGroup> = Vec::new();
    let mut icmp_rule: Option<&IselRule> = None;

    for rule in rules {
        match &rule.pattern {
            IrPattern::Binop { op, lhs, .. } => {
                let guard = lhs.ann;
                if let Some(group) = groups.iter_mut().find(|g| g.op_name == *op) {
                    group.rules.push((guard, rule));
                } else {
                    groups.push(OpGroup {
                        op_name: op.clone(),
                        rules: vec![(guard, rule)],
                    });
                }
            }
            IrPattern::Unop { op, .. } => {
                groups.push(OpGroup {
                    op_name: op.clone(),
                    rules: vec![(AnnGuard::Any, rule)],
                });
            }
            IrPattern::Icmp { .. } => {
                icmp_rule = Some(rule);
            }
        }
    }

    // Emit match arms for each Op variant.
    for group in &groups {
        let op_name = &group.op_name;
        let op_variant = op_variant_pattern(op_name);
        writeln!(out, "        {op_variant} => {{").unwrap();

        // Emit ensure_in_reg for operands.
        let operand_names = op_operand_names(op_name);
        for (var, field) in &operand_names {
            writeln!(
                out,
                "            let {var} = ctx.ensure_in_reg({field}.clone().raw().value)?;"
            )
            .unwrap();
        }

        if group.rules.len() == 1 && group.rules[0].0 == AnnGuard::Any {
            // Single rule, no annotation dispatch needed.
            let rule = group.rules[0].1;
            let args = operand_names
                .iter()
                .map(|(v, _)| v.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            let ann_regs = needs_annotation_params(rule);
            let ann_args: String = ann_regs
                .iter()
                .map(|r| format!(", {r}.clone().raw().annotation"))
                .collect::<Vec<_>>()
                .join("");
            writeln!(
                out,
                "            gen_{rule_name}(ctx, vref, {args}{ann_args})",
                rule_name = rule.name
            )
            .unwrap();
        } else {
            // Multiple rules with annotation guards — dispatch on lhs annotation.
            let first_field = &operand_names[0].1;
            writeln!(
                out,
                "            match {first_field}.clone().raw().annotation {{"
            )
            .unwrap();

            let mut has_any = false;

            for (guard, rule) in &group.rules {
                let args = operand_names
                    .iter()
                    .map(|(v, _)| v.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let ann_regs = needs_annotation_params(rule);
                let ann_args: String = ann_regs
                    .iter()
                    .map(|r| format!(", {r}.clone().raw().annotation"))
                    .collect::<Vec<_>>()
                    .join("");
                match guard {
                    AnnGuard::Signed => {
                        writeln!(
                            out,
                            "                Some(Annotation::Int(IntAnnotation {{ signedness: IntSignedness::Signed, .. }})) => gen_{rule_name}(ctx, vref, {args}{ann_args}),",
                            rule_name = rule.name
                        )
                        .unwrap();
                    }
                    AnnGuard::Unsigned => {
                        writeln!(
                            out,
                            "                Some(Annotation::Int(IntAnnotation {{ signedness: IntSignedness::Unsigned, .. }})) => gen_{rule_name}(ctx, vref, {args}{ann_args}),",
                            rule_name = rule.name
                        )
                        .unwrap();
                    }
                    AnnGuard::Any => {
                        has_any = true;
                        writeln!(
                            out,
                            "                _ => gen_{rule_name}(ctx, vref, {args}{ann_args}),",
                            rule_name = rule.name
                        )
                        .unwrap();
                    }
                }
            }

            if !has_any {
                // Find the unsigned rule as default, or the first rule.
                let default_rule = group
                    .rules
                    .iter()
                    .find(|(g, _)| *g == AnnGuard::Unsigned)
                    .or_else(|| group.rules.first())
                    .map(|(_, r)| *r)
                    .unwrap();
                let args = operand_names
                    .iter()
                    .map(|(v, _)| v.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                let ann_regs = needs_annotation_params(default_rule);
                let ann_args: String = ann_regs
                    .iter()
                    .map(|r| format!(", {r}.clone().raw().annotation"))
                    .collect::<Vec<_>>()
                    .join("");
                writeln!(
                    out,
                    "                _ => gen_{default_rule}(ctx, vref, {args}{ann_args}),",
                    default_rule = default_rule.name
                )
                .unwrap();
            }

            writeln!(out, "            }}").unwrap();
        }

        writeln!(out, "        }}").unwrap();
    }

    // ICmp arm.
    if let Some(rule) = icmp_rule {
        writeln!(out, "        Op::ICmp(cmp_op, lhs, rhs) => {{").unwrap();
        writeln!(
            out,
            "            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;"
        )
        .unwrap();
        writeln!(
            out,
            "            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;"
        )
        .unwrap();
        writeln!(
            out,
            "            gen_{name}(ctx, vref, l, r, *cmp_op, lhs.clone().raw().annotation)",
            name = rule.name
        )
        .unwrap();
        writeln!(out, "        }}").unwrap();
    }

    writeln!(out, "        _ => None,").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
}

/// Map an IR op name to its `Op::Xxx(lhs, rhs)` match pattern.
fn op_variant_pattern(op_name: &str) -> &'static str {
    match op_name {
        "Add" => "Op::Add(lhs, rhs)",
        "Sub" => "Op::Sub(lhs, rhs)",
        "Mul" => "Op::Mul(lhs, rhs)",
        "Or" => "Op::Or(lhs, rhs)",
        "And" => "Op::And(lhs, rhs)",
        "Xor" => "Op::Xor(lhs, rhs)",
        "BAnd" => "Op::BAnd(lhs, rhs)",
        "BOr" => "Op::BOr(lhs, rhs)",
        "BXor" => "Op::BXor(lhs, rhs)",
        "Shl" => "Op::Shl(lhs, rhs)",
        "Shr" => "Op::Shr(lhs, rhs)",
        "Min" => "Op::Min(lhs, rhs)",
        "Max" => "Op::Max(lhs, rhs)",
        "CountOnes" => "Op::CountOnes(val)",
        "CountLeadingZeros" => "Op::CountLeadingZeros(val, _)",
        "CountTrailingZeros" => "Op::CountTrailingZeros(val)",
        "PtrAdd" => "Op::PtrAdd(ptr, offset)",
        "PtrDiff" => "Op::PtrDiff(lhs, rhs)",
        _ => panic!("unknown op: {op_name}"),
    }
}

/// Map an IR op name to its operand variable names and field accessors.
fn op_operand_names(op_name: &str) -> Vec<(String, String)> {
    match op_name {
        "Add" | "Sub" | "Mul" | "Or" | "And" | "Xor" | "BAnd" | "BOr" | "BXor" | "Shl" | "Shr"
        | "Min" | "Max" | "PtrDiff" => {
            vec![
                ("l".to_string(), "lhs".to_string()),
                ("r".to_string(), "rhs".to_string()),
            ]
        }
        "CountOnes" | "CountLeadingZeros" | "CountTrailingZeros" => {
            vec![("s".to_string(), "val".to_string())]
        }
        "PtrAdd" => vec![
            ("p".to_string(), "ptr".to_string()),
            ("o".to_string(), "offset".to_string()),
        ],
        _ => panic!("unknown op: {op_name}"),
    }
}
