// @generated by tuffy_isel_gen -- DO NOT EDIT

use crate::inst::{CondCode, MInst, OpSize};
use crate::reg::Gpr;
use tuffy_ir::instruction::{ICmpOp, Op};
use tuffy_ir::types::{Annotation, IntAnnotation, IntSignedness};
use tuffy_ir::value::ValueRef;
use tuffy_regalloc::VReg;

/// Emit the machine instructions for the `add` rule.
fn gen_add(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::AddRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `sub` rule.
fn gen_sub(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::SubRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `mul` rule.
fn gen_mul(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::ImulRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `or` rule.
fn gen_or(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::OrRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `and` rule.
fn gen_and(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::AndRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `xor` rule.
fn gen_xor(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::XorRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `band` rule.
fn gen_band(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S8,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::AndRR {
        size: OpSize::S8,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `bor` rule.
fn gen_bor(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S8,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::OrRR {
        size: OpSize::S8,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `bxor` rule.
fn gen_bxor(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S8,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::XorRR {
        size: OpSize::S8,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `shl` rule.
fn gen_shl(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    let v1 = ctx.alloc.alloc_fixed(Gpr::Rcx.to_preg());
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v1,
        src: rhs,
    });
    let size_2 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::ShlRCL {
        size: size_2,
        dst: v0,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `shr_signed` rule.
fn gen_shr_signed(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    let v1 = ctx.alloc.alloc_fixed(Gpr::Rcx.to_preg());
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v1,
        src: rhs,
    });
    let size_2 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::SarRCL {
        size: size_2,
        dst: v0,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `shr_unsigned` rule.
fn gen_shr_unsigned(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    let v1 = ctx.alloc.alloc_fixed(Gpr::Rcx.to_preg());
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v1,
        src: rhs,
    });
    let size_2 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::ShrRCL {
        size: size_2,
        dst: v0,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `min_signed` rule.
fn gen_min_signed(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    let size_1 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::CmpRR {
        size: size_1,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::L,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `min_unsigned` rule.
fn gen_min_unsigned(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    let size_1 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::CmpRR {
        size: size_1,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::B,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `max_signed` rule.
fn gen_max_signed(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    let size_1 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::CmpRR {
        size: size_1,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::G,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `max_unsigned` rule.
fn gen_max_unsigned(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    let size_1 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::CmpRR {
        size: size_1,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::A,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `count_ones` rule.
fn gen_count_ones(ctx: &mut super::IselCtx, vref: ValueRef, src: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::Popcnt {
        size: OpSize::S64,
        dst: v0,
        src,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `count_leading_zeros` rule.
fn gen_count_leading_zeros(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    src: VReg,
    src_ann: Option<Annotation>,
) -> Option<()> {
    let size_0 = match src_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::Lzcnt {
        size: size_0,
        dst: v0,
        src,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `count_trailing_zeros` rule.
fn gen_count_trailing_zeros(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    src: VReg,
    src_ann: Option<Annotation>,
) -> Option<()> {
    let size_0 = match src_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::Tzcnt {
        size: size_0,
        dst: v0,
        src,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `icmp` rule.
fn gen_icmp(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    cmp_op: ICmpOp,
    lhs_ann: Option<Annotation>,
) -> Option<()> {
    let size_0 = match lhs_ann {
        Some(Annotation::Int(int_ann)) => match int_ann.bit_width {
            8 => OpSize::S8,
            16 => OpSize::S16,
            32 => OpSize::S32,
            _ => OpSize::S64,
        },
        _ => OpSize::S64,
    };
    ctx.out.push(MInst::CmpRR {
        size: size_0,
        src1: lhs,
        src2: rhs,
    });
    let int_ann = lhs_ann.and_then(|a| {
        if let Annotation::Int(ia) = a {
            Some(ia)
        } else {
            None
        }
    });
    let cc = super::icmp_to_cc(cmp_op, int_ann);
    let tmp_cc = ctx.alloc.alloc();
    let dst = ctx.alloc.alloc();
    ctx.out.push(MInst::SetCC { cc, dst: tmp_cc });
    ctx.out.push(MInst::MovzxB { dst, src: tmp_cc });
    ctx.regs.assign(vref, dst);
    Some(())
}

/// Emit the machine instructions for the `ptr_add` rule.
fn gen_ptr_add(ctx: &mut super::IselCtx, vref: ValueRef, ptr: VReg, offset: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: ptr,
    });
    ctx.out.push(MInst::AddRR {
        size: OpSize::S64,
        dst: v0,
        src: offset,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

/// Emit the machine instructions for the `ptr_diff` rule.
fn gen_ptr_diff(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::SubRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

#[allow(
    unused_variables,
    reason = "Generated selector arms do not consume every bound operand in every rule."
)]
/// Try the generated instruction-selection rules for a single IR operation.
pub(super) fn try_select_generated(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    op: &Op,
    func: &super::Function,
) -> Option<()> {
    match op {
        Op::Add(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_add(ctx, vref, l, r)
        }
        Op::Sub(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_sub(ctx, vref, l, r)
        }
        Op::Mul(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_mul(ctx, vref, l, r)
        }
        Op::Or(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_or(ctx, vref, l, r)
        }
        Op::And(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_and(ctx, vref, l, r)
        }
        Op::Xor(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_xor(ctx, vref, l, r)
        }
        Op::BAnd(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_band(ctx, vref, l, r)
        }
        Op::BOr(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_bor(ctx, vref, l, r)
        }
        Op::BXor(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_bxor(ctx, vref, l, r)
        }
        Op::Shl(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_shl(
                ctx,
                vref,
                l,
                r,
                lhs.clone().raw().annotation.or_else(|| {
                    super::get_int_annotation(func, lhs.clone().raw().value).map(Annotation::Int)
                }),
            )
        }
        Op::Shr(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            match lhs.clone().raw().annotation {
                Some(Annotation::Int(IntAnnotation {
                    signedness: IntSignedness::Signed,
                    ..
                })) => gen_shr_signed(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
                Some(Annotation::Int(IntAnnotation {
                    signedness: IntSignedness::Unsigned,
                    ..
                })) => gen_shr_unsigned(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
                _ => gen_shr_unsigned(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
            }
        }
        Op::Min(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            match lhs.clone().raw().annotation {
                Some(Annotation::Int(IntAnnotation {
                    signedness: IntSignedness::Signed,
                    ..
                })) => gen_min_signed(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
                Some(Annotation::Int(IntAnnotation {
                    signedness: IntSignedness::Unsigned,
                    ..
                })) => gen_min_unsigned(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
                _ => gen_min_unsigned(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
            }
        }
        Op::Max(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            match lhs.clone().raw().annotation {
                Some(Annotation::Int(IntAnnotation {
                    signedness: IntSignedness::Signed,
                    ..
                })) => gen_max_signed(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
                Some(Annotation::Int(IntAnnotation {
                    signedness: IntSignedness::Unsigned,
                    ..
                })) => gen_max_unsigned(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
                _ => gen_max_unsigned(
                    ctx,
                    vref,
                    l,
                    r,
                    lhs.clone().raw().annotation.or_else(|| {
                        super::get_int_annotation(func, lhs.clone().raw().value)
                            .map(Annotation::Int)
                    }),
                ),
            }
        }
        Op::CountOnes(val) => {
            let s = ctx.ensure_in_reg(val.clone().raw().value)?;
            gen_count_ones(ctx, vref, s)
        }
        Op::CountLeadingZeros(val, _) => {
            let s = ctx.ensure_in_reg(val.clone().raw().value)?;
            gen_count_leading_zeros(
                ctx,
                vref,
                s,
                val.clone().raw().annotation.or_else(|| {
                    super::get_int_annotation(func, val.clone().raw().value).map(Annotation::Int)
                }),
            )
        }
        Op::CountTrailingZeros(val) => {
            let s = ctx.ensure_in_reg(val.clone().raw().value)?;
            gen_count_trailing_zeros(
                ctx,
                vref,
                s,
                val.clone().raw().annotation.or_else(|| {
                    super::get_int_annotation(func, val.clone().raw().value).map(Annotation::Int)
                }),
            )
        }
        Op::PtrAdd(ptr, offset) => {
            let p = ctx.ensure_in_reg(ptr.clone().raw().value)?;
            let o = ctx.ensure_in_reg(offset.clone().raw().value)?;
            gen_ptr_add(ctx, vref, p, o)
        }
        Op::PtrDiff(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_ptr_diff(ctx, vref, l, r)
        }
        Op::ICmp(cmp_op, lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.clone().raw().value)?;
            let r = ctx.ensure_in_reg(rhs.clone().raw().value)?;
            gen_icmp(
                ctx,
                vref,
                l,
                r,
                *cmp_op,
                lhs.clone().raw().annotation.or_else(|| {
                    super::get_int_annotation(func, lhs.clone().raw().value).map(Annotation::Int)
                }),
            )
        }
        _ => None,
    }
}
