// @generated by tuffy_isel_gen -- DO NOT EDIT

use crate::inst::{CondCode, MInst, OpSize};
use crate::reg::Gpr;
use tuffy_ir::instruction::{ICmpOp, Op};
use tuffy_ir::types::IntAnnotation;
use tuffy_ir::value::ValueRef;
use tuffy_regalloc::VReg;

fn get_int_annotation(func: &tuffy_ir::function::Function, val: ValueRef) -> Option<IntAnnotation> {
    if val.is_block_arg() {
        let ty = &func.block_args.get(val.index() as usize)?.ty;
        match ty {
            tuffy_ir::types::Type::Int(ann) => Some(*ann),
            _ => None,
        }
    } else if val.is_secondary_result() {
        let ty = func
            .instructions
            .get(val.inst_index() as usize)?
            .secondary_ty
            .as_ref()?;
        match ty {
            tuffy_ir::types::Type::Int(ann) => Some(*ann),
            _ => None,
        }
    } else {
        let ty = &func.instructions.get(val.index() as usize)?.ty;
        match ty {
            tuffy_ir::types::Type::Int(ann) => Some(*ann),
            _ => None,
        }
    }
}

fn bits_to_opsize(bits: u32) -> OpSize {
    match bits {
        8 => OpSize::S8,
        16 => OpSize::S16,
        32 => OpSize::S32,
        _ => OpSize::S64,
    }
}

fn int_ann_to_opsize(ann: Option<IntAnnotation>) -> OpSize {
    match ann {
        Some(a) => bits_to_opsize(a.bit_width),
        None => OpSize::S64,
    }
}

fn gen_add(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::AddRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_sub(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::SubRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_mul(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::ImulRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_or(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::OrRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_and(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::AndRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_xor(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::XorRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_shl(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    let v1 = ctx.alloc.alloc_fixed(Gpr::Rcx.to_preg());
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v1,
        src: rhs,
    });
    ctx.out.push(MInst::ShlRCL {
        size: OpSize::S64,
        dst: v0,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_shr_signed(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<IntAnnotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    let v1 = ctx.alloc.alloc_fixed(Gpr::Rcx.to_preg());
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v1,
        src: rhs,
    });
    let size_2 = int_ann_to_opsize(lhs_ann);
    ctx.out.push(MInst::SarRCL {
        size: size_2,
        dst: v0,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_shr_unsigned(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    lhs_ann: Option<IntAnnotation>,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    let v1 = ctx.alloc.alloc_fixed(Gpr::Rcx.to_preg());
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v1,
        src: rhs,
    });
    let size_2 = int_ann_to_opsize(lhs_ann);
    ctx.out.push(MInst::ShrRCL {
        size: size_2,
        dst: v0,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_min_signed(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    size: OpSize,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.out.push(MInst::CmpRR {
        size,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::L,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_min_unsigned(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    size: OpSize,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.out.push(MInst::CmpRR {
        size,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::B,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_max_signed(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    size: OpSize,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.out.push(MInst::CmpRR {
        size,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::G,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_max_unsigned(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    size: OpSize,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.out.push(MInst::CmpRR {
        size,
        src1: lhs,
        src2: rhs,
    });
    ctx.out.push(MInst::CMOVcc {
        size: OpSize::S64,
        cc: CondCode::A,
        dst: v0,
        src: lhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_count_ones(ctx: &mut super::IselCtx, vref: ValueRef, src: VReg, size: OpSize) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::Popcnt { size, dst: v0, src });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_count_leading_zeros(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    src: VReg,
    size: OpSize,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::Lzcnt { size, dst: v0, src });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_count_trailing_zeros(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    src: VReg,
    size: OpSize,
) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::Tzcnt { size, dst: v0, src });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_icmp(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    lhs: VReg,
    rhs: VReg,
    cmp_op: ICmpOp,
    lhs_ann: Option<IntAnnotation>,
) -> Option<()> {
    let size = int_ann_to_opsize(lhs_ann);
    ctx.out.push(MInst::CmpRR {
        size,
        src1: lhs,
        src2: rhs,
    });
    let cc = super::icmp_to_cc(cmp_op, lhs_ann);
    // Keep the deferred cc for BrIf (which uses flags directly).
    ctx.cmps.set(vref, cc);
    // Also materialize immediately into a register. Without this, when multiple
    // ICmps feed a Select (e.g. 128-bit comparisons), a later CmpRR overwrites
    // the flags before ensure_in_reg/select_select can consume them, producing
    // wrong values. Once the value is in a register, ensure_in_reg returns it
    // directly without re-reading stale flags.
    //
    // Use two separate VRegs: `tmp_cc` for the raw SetCC output (low byte only,
    // upper bytes are undefined/garbage from the previous value), and `dst` for
    // the zero-extended result from MovzxB.  If the allocator spills `tmp_cc`
    // before MovzxB runs, the spill slot has garbage upper bytes — but MovzxB
    // only reads the low byte, so that is harmless.  `dst` is defined solely by
    // MovzxB, so its spill slot is always written with the correct 0/1 value.
    let tmp_cc = ctx.alloc.alloc();
    let dst = ctx.alloc.alloc();
    ctx.out.push(MInst::SetCC { cc, dst: tmp_cc });
    ctx.out.push(MInst::MovzxB { dst, src: tmp_cc });
    ctx.regs.assign(vref, dst);
    Some(())
}

fn gen_ptr_add(ctx: &mut super::IselCtx, vref: ValueRef, ptr: VReg, offset: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: ptr,
    });
    ctx.out.push(MInst::AddRR {
        size: OpSize::S64,
        dst: v0,
        src: offset,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

fn gen_ptr_diff(ctx: &mut super::IselCtx, vref: ValueRef, lhs: VReg, rhs: VReg) -> Option<()> {
    let v0 = ctx.alloc.alloc();
    ctx.out.push(MInst::MovRR {
        size: OpSize::S64,
        dst: v0,
        src: lhs,
    });
    ctx.out.push(MInst::SubRR {
        size: OpSize::S64,
        dst: v0,
        src: rhs,
    });
    ctx.regs.assign(vref, v0);
    Some(())
}

#[allow(unused_variables)]
pub(super) fn try_select_generated(
    ctx: &mut super::IselCtx,
    vref: ValueRef,
    op: &Op,
    func: &tuffy_ir::function::Function,
) -> Option<()> {
    match op {
        Op::Add(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_add(ctx, vref, l, r)
        }
        Op::Sub(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_sub(ctx, vref, l, r)
        }
        Op::Mul(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_mul(ctx, vref, l, r)
        }
        Op::Or(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_or(ctx, vref, l, r)
        }
        Op::And(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_and(ctx, vref, l, r)
        }
        Op::Xor(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_xor(ctx, vref, l, r)
        }
        Op::Shl(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_shl(ctx, vref, l, r)
        }
        Op::Shr(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            let lhs_ann = get_int_annotation(func, lhs.value);
            match lhs_ann {
                Some(ann) if matches!(ann.signedness, tuffy_ir::types::IntSignedness::Signed) => {
                    gen_shr_signed(ctx, vref, l, r, lhs_ann)
                }
                _ => gen_shr_unsigned(ctx, vref, l, r, lhs_ann),
            }
        }
        Op::Min(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            let lhs_ann = get_int_annotation(func, lhs.value);
            let size = int_ann_to_opsize(lhs_ann);
            match lhs_ann {
                Some(ann) if matches!(ann.signedness, tuffy_ir::types::IntSignedness::Signed) => {
                    gen_min_signed(ctx, vref, l, r, size)
                }
                _ => gen_min_unsigned(ctx, vref, l, r, size),
            }
        }
        Op::Max(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            let lhs_ann = get_int_annotation(func, lhs.value);
            let size = int_ann_to_opsize(lhs_ann);
            match lhs_ann {
                Some(ann) if matches!(ann.signedness, tuffy_ir::types::IntSignedness::Signed) => {
                    gen_max_signed(ctx, vref, l, r, size)
                }
                _ => gen_max_unsigned(ctx, vref, l, r, size),
            }
        }
        Op::CountOnes(val) => {
            let s = ctx.ensure_in_reg(val.value)?;
            let val_ann = get_int_annotation(func, val.value);
            let size = int_ann_to_opsize(val_ann);
            gen_count_ones(ctx, vref, s, size)
        }
        Op::CountLeadingZeros(val, bits) => {
            let s = ctx.ensure_in_reg(val.value)?;
            let size = bits_to_opsize(*bits);
            gen_count_leading_zeros(ctx, vref, s, size)
        }
        Op::CountTrailingZeros(val) => {
            let s = ctx.ensure_in_reg(val.value)?;
            let val_ann = get_int_annotation(func, val.value);
            let size = int_ann_to_opsize(val_ann);
            gen_count_trailing_zeros(ctx, vref, s, size)
        }
        Op::PtrAdd(ptr, offset) => {
            let p = ctx.ensure_in_reg(ptr.value)?;
            let o = ctx.ensure_in_reg(offset.value)?;
            gen_ptr_add(ctx, vref, p, o)
        }
        Op::PtrDiff(lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            gen_ptr_diff(ctx, vref, l, r)
        }
        Op::ICmp(cmp_op, lhs, rhs) => {
            let l = ctx.ensure_in_reg(lhs.value)?;
            let r = ctx.ensure_in_reg(rhs.value)?;
            let lhs_ann = get_int_annotation(func, lhs.value);
            gen_icmp(ctx, vref, l, r, *cmp_op, lhs_ann)
        }
        _ => None,
    }
}
