//! Generate the at-use fact propagation runtime from validated schema data.

use std::fmt::Write;

use crate::GenerateError;
use crate::schema::{
    AtUseForwardRule, AtUseKnownBitsForwardKind, AtUseSummaryForwardKind, AtUseTransformKind,
    PeepholeSpec,
};

/// Generate the at-use fact and transform source file.
///
/// # Errors
///
/// Returns an error if the schema uses an unsupported at-use transfer rule.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
pub fn generate(spec: &PeepholeSpec) -> Result<String, GenerateError> {
    let mut out = String::new();
    writeln!(out, "// @generated by tuffy_opt_gen -- DO NOT EDIT").unwrap();
    writeln!(out).unwrap();
    generate_forward(&mut out, spec)?;
    writeln!(out).unwrap();
    generate_transforms(&mut out, spec);
    Ok(out)
}

/// Emit the generated at-use forward-fact function.
///
/// # Errors
///
/// Returns an error if a forward rule uses an unsupported opcode or transfer.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn generate_forward(out: &mut String, spec: &PeepholeSpec) -> Result<(), GenerateError> {
    writeln!(
        out,
        "/// Compute generated at-use facts for one value when a specialized rule exists."
    )
    .unwrap();
    writeln!(
        out,
        "fn generated_forward_at_use_facts(func: &Function, value: ValueRef, current: &FactMap) -> Option<AtUseFacts> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    if value.is_block_arg() || value.is_secondary_result() {{ return None; }}"
    )
    .unwrap();
    writeln!(out, "    let node = func.inst_pool.get(value.index())?;").unwrap();
    writeln!(out, "    let facts = match &node.inst.op {{").unwrap();
    for rule in &spec.at_use_forward_rules {
        emit_forward_arm(out, rule)?;
    }
    writeln!(out, "        _ => forward_unknown(),").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(out, "    Some(facts)").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

/// Emit one `match` arm for an at-use forward rule.
///
/// # Errors
///
/// Returns an error if the rule uses an unsupported opcode or transfer.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn emit_forward_arm(out: &mut String, rule: &AtUseForwardRule) -> Result<(), GenerateError> {
    let helper = forward_helper_name(rule)?;
    let line = match rule.op.as_str() {
        "const" => format!(
            "        // {}\n        Op::Const(value) => {helper}(value),",
            rule.proof_ref
        ),
        "select" => format!(
            "        // {}\n        Op::Select(_, true_value, false_value) => {helper}(func, current, true_value, false_value),",
            rule.proof_ref
        ),
        "and" => format!(
            "        // {}\n        Op::And(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "or" => format!(
            "        // {}\n        Op::Or(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "xor" => format!(
            "        // {}\n        Op::Xor(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        other => {
            return Err(GenerateError::UnsupportedFactsRule(format!(
                "unsupported at-use forward op `{other}`"
            )));
        }
    };
    writeln!(out, "{line}").unwrap();
    Ok(())
}

/// Resolve the runtime helper name for an at-use forward rule.
///
/// # Errors
///
/// Returns an error if the rule requests an unsupported transfer-function
/// combination.
fn forward_helper_name(rule: &AtUseForwardRule) -> Result<&'static str, GenerateError> {
    match (rule.known_bits_forward, rule.summary_forward) {
        (AtUseKnownBitsForwardKind::Unknown, AtUseSummaryForwardKind::Unknown) => {
            Ok("forward_unknown")
        }
        (AtUseKnownBitsForwardKind::Const, AtUseSummaryForwardKind::Const) => Ok("forward_const"),
        (AtUseKnownBitsForwardKind::Select, AtUseSummaryForwardKind::Select) => {
            Ok("forward_select")
        }
        (AtUseKnownBitsForwardKind::BitAnd, AtUseSummaryForwardKind::BitAnd) => {
            Ok("forward_bitand")
        }
        (AtUseKnownBitsForwardKind::BitOr, AtUseSummaryForwardKind::BitOr) => Ok("forward_bitor"),
        (AtUseKnownBitsForwardKind::BitXor, AtUseSummaryForwardKind::BitXor) => {
            Ok("forward_bitxor")
        }
        other => Err(GenerateError::UnsupportedFactsRule(format!(
            "unsupported at-use forward kind combination: {other:?}"
        ))),
    }
}

/// Emit the generated transform descriptor table.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn generate_transforms(out: &mut String, spec: &PeepholeSpec) {
    writeln!(
        out,
        "#[allow(dead_code, reason = \"Generated descriptor counts may be used only by selected tests or runtimes.\")]"
    )
    .unwrap();
    writeln!(
        out,
        "/// Number of generated at-use transforms compiled into this module."
    )
    .unwrap();
    writeln!(
        out,
        "pub(super) const GENERATED_AT_USE_TRANSFORM_COUNT: usize = {};",
        spec.at_use_transforms.len()
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "/// Descriptors for every generated at-use transform.").unwrap();
    writeln!(
        out,
        "pub(super) const GENERATED_AT_USE_TRANSFORMS: &[AtUseTransformDescriptor] = &["
    )
    .unwrap();
    for transform in &spec.at_use_transforms {
        let kind = transform_kind_name(transform.kind);
        writeln!(
            out,
            "    AtUseTransformDescriptor {{ name: {:?}, kind: AtUseTransformKind::{kind}, proof_ref: {:?} }},",
            transform.name, transform.proof_ref
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

/// Render the runtime enum variant name for an at-use transform.
fn transform_kind_name(kind: AtUseTransformKind) -> &'static str {
    match kind {
        AtUseTransformKind::FoldIcmp => "FoldIcmp",
        AtUseTransformKind::FoldBrIf => "FoldBrIf",
        AtUseTransformKind::StrengthenOperand => "StrengthenOperand",
        AtUseTransformKind::StrengthenResult => "StrengthenResult",
    }
}
