use std::fmt::Write;

use crate::GenerateError;
use crate::at_use_schema::{
    AtUseSpec, ForwardRule, KnownBitsForwardKind, SummaryForwardKind, TransformKind,
};

pub fn generate(spec: &AtUseSpec) -> Result<String, GenerateError> {
    let mut out = String::new();
    writeln!(out, "// @generated by tuffy_opt_gen -- DO NOT EDIT").unwrap();
    writeln!(out).unwrap();
    generate_forward(&mut out, spec)?;
    writeln!(out).unwrap();
    generate_transforms(&mut out, spec);
    Ok(out)
}

fn generate_forward(out: &mut String, spec: &AtUseSpec) -> Result<(), GenerateError> {
    writeln!(
        out,
        "fn generated_forward_at_use_facts(func: &Function, value: ValueRef, current: &FactMap) -> Option<AtUseFacts> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    if value.is_block_arg() || value.is_secondary_result() {{ return None; }}"
    )
    .unwrap();
    writeln!(out, "    let node = func.inst_pool.get(value.index())?;").unwrap();
    writeln!(out, "    let facts = match &node.inst.op {{").unwrap();
    for rule in &spec.forward_rules {
        emit_forward_arm(out, rule)?;
    }
    writeln!(out, "        _ => forward_unknown(),").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(out, "    Some(facts)").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn emit_forward_arm(out: &mut String, rule: &ForwardRule) -> Result<(), GenerateError> {
    let helper = forward_helper_name(rule)?;
    let line = match rule.op.as_str() {
        "const" => format!(
            "        // {}\n        Op::Const(value) => {helper}(value),",
            rule.proof_ref
        ),
        "select" => format!(
            "        // {}\n        Op::Select(_, true_value, false_value) => {helper}(func, current, true_value, false_value),",
            rule.proof_ref
        ),
        "and" => format!(
            "        // {}\n        Op::And(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "or" => format!(
            "        // {}\n        Op::Or(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "xor" => format!(
            "        // {}\n        Op::Xor(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        other => {
            return Err(GenerateError::UnsupportedFactsRule(format!(
                "unsupported at-use forward op `{other}`"
            )));
        }
    };
    writeln!(out, "{line}").unwrap();
    Ok(())
}

fn forward_helper_name(rule: &ForwardRule) -> Result<&'static str, GenerateError> {
    match (rule.known_bits_forward, rule.summary_forward) {
        (KnownBitsForwardKind::Unknown, SummaryForwardKind::Unknown) => Ok("forward_unknown"),
        (KnownBitsForwardKind::Const, SummaryForwardKind::Const) => Ok("forward_const"),
        (KnownBitsForwardKind::Select, SummaryForwardKind::Select) => Ok("forward_select"),
        (KnownBitsForwardKind::BitAnd, SummaryForwardKind::BitAnd) => Ok("forward_bitand"),
        (KnownBitsForwardKind::BitOr, SummaryForwardKind::BitOr) => Ok("forward_bitor"),
        (KnownBitsForwardKind::BitXor, SummaryForwardKind::BitXor) => Ok("forward_bitxor"),
        other => Err(GenerateError::UnsupportedFactsRule(format!(
            "unsupported at-use forward kind combination: {other:?}"
        ))),
    }
}

fn generate_transforms(out: &mut String, spec: &AtUseSpec) {
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(
        out,
        "pub(super) const GENERATED_AT_USE_TRANSFORM_COUNT: usize = {};",
        spec.transforms.len()
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "pub(super) const GENERATED_AT_USE_TRANSFORMS: &[AtUseTransformDescriptor] = &["
    )
    .unwrap();
    for transform in &spec.transforms {
        let kind = transform_kind_name(transform.kind);
        writeln!(
            out,
            "    AtUseTransformDescriptor {{ name: {:?}, kind: AtUseTransformKind::{kind}, proof_ref: {:?} }},",
            transform.name, transform.proof_ref
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn transform_kind_name(kind: TransformKind) -> &'static str {
    match kind {
        TransformKind::FoldIcmp => "FoldIcmp",
        TransformKind::FoldBrIf => "FoldBrIf",
        TransformKind::StrengthenOperand => "StrengthenOperand",
        TransformKind::StrengthenResult => "StrengthenResult",
    }
}
