//! Generate the main peephole rewrite runtime from validated schema data.

use std::fmt::Write;

use num_bigint::BigInt;

use crate::GenerateError;
use crate::schema::{
    CanonicalBrIfMode, IntAnnotationSpec, IntPredicate, MatchRoot, Pattern, PatternAttr,
    PeepholeRule, PeepholeSpec, Replacement, RootReplacement, SideCondition, ValueType,
};

/// Generate the main peephole rewrite source file.
///
/// # Errors
///
/// Returns an error if a rule uses an unsupported schema feature.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
pub fn generate(spec: &PeepholeSpec) -> Result<String, GenerateError> {
    let mut out = String::new();
    writeln!(out, "// @generated by tuffy_opt_gen -- DO NOT EDIT").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/// Number of generated peephole rules compiled into this module."
    )
    .unwrap();
    writeln!(
        out,
        "pub(super) const GENERATED_RULE_COUNT: usize = {};",
        spec.rules.len()
    )
    .unwrap();
    writeln!(out).unwrap();

    for rule in &spec.rules {
        generate_rule_fn(&mut out, rule)?;
    }

    generate_dispatch(&mut out, &spec.rules);

    Ok(out)
}

/// Generate the top-level generated rule dispatcher.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn generate_dispatch(out: &mut String, rules: &[PeepholeRule]) {
    writeln!(
        out,
        "#[allow(clippy::question_mark, reason = \"The generated dispatcher prefers straight-line early returns for readability.\")]"
    )
    .unwrap();
    writeln!(
        out,
        "/// Try each generated peephole rule against the selected root instruction."
    )
    .unwrap();
    writeln!(
        out,
        "pub(super) fn try_apply_generated_rule(func: &mut Function, root_idx: u32, stats: &mut PeepholeStats, fact_cache: &mut IntFactCache) -> bool {{"
    )
    .unwrap();
    if rules.is_empty() {
        writeln!(out, "    let _ = (func, root_idx, stats, fact_cache);").unwrap();
        writeln!(out, "    false").unwrap();
    } else {
        for rule in rules {
            let ident = rule_ident(&rule.name);
            writeln!(
                out,
                "    if try_apply_{ident}(func, root_idx, stats, fact_cache) {{ return true; }}"
            )
            .unwrap();
        }
        writeln!(out, "    false").unwrap();
    }
    writeln!(out, "}}").unwrap();
}

/// Generate one rule-specific matcher and rewriter helper.
///
/// # Errors
///
/// Returns an error if the rule uses an unsupported schema feature.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn generate_rule_fn(out: &mut String, rule: &PeepholeRule) -> Result<(), GenerateError> {
    let ident = rule_ident(&rule.name);
    let mut bindings = Vec::new();
    match &rule.rewrite.match_root {
        MatchRoot::Value { root } => root.collect_bindings(&mut bindings),
        MatchRoot::Terminator { operands, .. } => {
            for operand in operands {
                operand.collect_bindings(&mut bindings);
            }
        }
        MatchRoot::CanonicalBrIf { binding, .. } => bindings.push(binding.as_str()),
        MatchRoot::ConstFold { .. } => {}
    }

    writeln!(
        out,
        "#[allow(clippy::question_mark, unused_parens, clippy::double_parens, reason = \"Generated matchers favor explicit Option control flow and mechanically-emitted parentheses.\")]"
    )
    .unwrap();
    writeln!(out, "/// Try the generated `{}` peephole rule.", rule.name).unwrap();
    writeln!(
        out,
        "fn try_apply_{ident}(func: &mut Function, root_idx: u32, stats: &mut PeepholeStats, fact_cache: &mut IntFactCache) -> bool {{"
    )
    .unwrap();
    writeln!(out, "    let _ = &mut *fact_cache;").unwrap();
    match (&rule.rewrite.match_root, &rule.rewrite.replacement) {
        (MatchRoot::Value { root }, RootReplacement::Value { value: replacement }) => {
            for binding in &bindings {
                writeln!(out, "    let mut bind_{binding}: Option<ValueRef> = None;").unwrap();
            }
            writeln!(out, "    let mut matched_insts = BTreeSet::new();").unwrap();
            writeln!(out, "    let replacement = (|| -> Option<ValueRewrite> {{").unwrap();
            writeln!(
                out,
                "        let Some(root_node) = func.inst_pool.get(root_idx) else {{ return None; }};"
            )
            .unwrap();
            writeln!(out, "        let root_block = root_node.parent_block;").unwrap();
            writeln!(
                out,
                "        let root_value = ValueRef::inst_result(root_idx);"
            )
            .unwrap();
            let mut pattern_gen = PatternGen::new(2);
            pattern_gen.emit_pattern(out, root, "root_value")?;
            emit_side_condition_checks(out, &rule.side_conditions)?;
            writeln!(
                out,
                "        let replacement = {};",
                value_rewrite_expr(replacement)?
            )
            .unwrap();
            writeln!(out, "        Some(replacement)").unwrap();
            writeln!(out, "    }})();").unwrap();
            writeln!(
                out,
                "    let Some(replacement) = replacement else {{ return false; }};"
            )
            .unwrap();
            writeln!(
                out,
                "    apply_value_root_rewrite(func, root_idx, replacement, &matched_insts);"
            )
            .unwrap();
        }
        (
            MatchRoot::Terminator {
                op,
                operands,
                successor_count,
            },
            RootReplacement::Terminator {
                op: replacement_op,
                operands: replacement_operands,
                successors,
            },
        ) => {
            let terminator_kind = classify_terminator_kind(op, *successor_count)?;
            let replacement_kind = classify_terminator_kind(replacement_op, successors.len())?;
            if terminator_kind != replacement_kind {
                return Err(GenerateError::UnsupportedRootRewrite {
                    rule: rule.name.clone(),
                    message: format!(
                        "terminator root `{op}` cannot be replaced with `{replacement_op}`"
                    ),
                });
            }
            for binding in &bindings {
                writeln!(out, "    let mut bind_{binding}: Option<ValueRef> = None;").unwrap();
            }
            writeln!(out, "    let mut matched_insts = BTreeSet::new();").unwrap();
            writeln!(
                out,
                "    let replacement = (|| -> Option<ReplacementTerminator> {{"
            )
            .unwrap();
            writeln!(
                out,
                "        let Some(root_node) = func.inst_pool.get(root_idx) else {{ return None; }};"
            )
            .unwrap();
            writeln!(out, "        let root_block = root_node.parent_block;").unwrap();
            emit_terminator_root_match(out, terminator_kind, operands)?;
            emit_side_condition_checks(out, &rule.side_conditions)?;
            emit_terminator_replacement(out, replacement_kind, replacement_operands, successors)?;
            writeln!(out, "    }})();").unwrap();
            writeln!(
                out,
                "    let Some(replacement) = replacement else {{ return false; }};"
            )
            .unwrap();
            writeln!(
                out,
                "    apply_terminator_root_rewrite(func, root_idx, replacement, &matched_insts);"
            )
            .unwrap();
        }
        (
            MatchRoot::CanonicalBrIf { binding, mode },
            RootReplacement::Terminator {
                op,
                operands,
                successors,
            },
        ) => {
            let replacement_kind = classify_terminator_kind(op, successors.len())?;
            if replacement_kind != TerminatorKind::BrIf {
                return Err(GenerateError::UnsupportedRootRewrite {
                    rule: rule.name.clone(),
                    message: "canonical brif roots only support brif replacements".to_string(),
                });
            }
            for binding in &bindings {
                writeln!(out, "    let mut bind_{binding}: Option<ValueRef> = None;").unwrap();
            }
            writeln!(
                out,
                "    let replacement = (|| -> Option<(ReplacementTerminator, BTreeSet<u32>)> {{"
            )
            .unwrap();
            writeln!(
                out,
                "        let canonical_match = try_match_canonical_brif(func, root_idx, {})?;",
                canonical_brif_mode_expr(*mode)
            )
            .unwrap();
            writeln!(
                out,
                "        if !bind_value_slot(&mut bind_{binding}, canonical_match.cond) {{ return None; }}"
            )
            .unwrap();
            emit_side_condition_checks(out, &rule.side_conditions)?;
            emit_canonical_brif_replacement(out, operands, successors)?;
            writeln!(
                out,
                "        Some((replacement, canonical_match.matched_insts))"
            )
            .unwrap();
            writeln!(out, "    }})();").unwrap();
            writeln!(
                out,
                "    let Some((replacement, matched_insts)) = replacement else {{ return false; }};"
            )
            .unwrap();
            writeln!(
                out,
                "    apply_terminator_root_rewrite(func, root_idx, replacement, &matched_insts);"
            )
            .unwrap();
        }
        (MatchRoot::ConstFold { op, attrs }, RootReplacement::ConstFold) => {
            let kind = classify_const_fold(op, attrs)?;
            writeln!(
                out,
                "    let Some(fold_match) = try_fold_constant_root(func, root_idx, {}) else {{ return false; }};",
                const_fold_kind_expr(kind)
            )
            .unwrap();
            writeln!(
                out,
                "    apply_value_root_rewrite(func, root_idx, fold_match.replacement, &fold_match.matched_insts);"
            )
            .unwrap();
        }
        _ => {
            return Err(GenerateError::UnsupportedRootRewrite {
                rule: rule.name.clone(),
                message: "root kind and replacement kind must match".to_string(),
            });
        }
    }
    writeln!(out, "    stats.record({:?});", rule.name).unwrap();
    writeln!(out, "    true").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

/// Render the runtime enum expression for a canonical `brif` mode.
fn canonical_brif_mode_expr(mode: CanonicalBrIfMode) -> &'static str {
    match mode {
        CanonicalBrIfMode::BoolXorConst => "CanonicalBrIfMode::BoolXorConst",
        CanonicalBrIfMode::IntifiedBoolCompare => "CanonicalBrIfMode::IntifiedBoolCompare",
    }
}

/// Emit the match prelude for a terminator-root pattern.
///
/// # Errors
///
/// Returns an error if the root shape is unsupported.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn emit_terminator_root_match(
    out: &mut String,
    kind: TerminatorKind,
    operands: &[Pattern],
) -> Result<(), GenerateError> {
    match kind {
        TerminatorKind::BrIf => {
            writeln!(
                out,
                "        let root_op_arg_0 = match &root_node.inst.op {{"
            )
            .unwrap();
            writeln!(
                out,
                "            Op::BrIf(cond, _, _, _, _) => cond.clone().raw().value,"
            )
            .unwrap();
            writeln!(out, "            _ => return None,").unwrap();
            writeln!(out, "        }};").unwrap();
            let mut pattern_gen = PatternGen::new(2);
            if operands.len() != 1 {
                return Err(GenerateError::UnsupportedPattern(
                    "brif root currently expects exactly one matched operand".to_string(),
                ));
            }
            pattern_gen.emit_pattern(out, &operands[0], "root_op_arg_0")?;
        }
    }
    Ok(())
}

/// Emit a replacement for canonical `brif` matches.
///
/// # Errors
///
/// Returns an error if the replacement shape is unsupported.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn emit_canonical_brif_replacement(
    out: &mut String,
    operands: &[Replacement],
    successors: &[usize],
) -> Result<(), GenerateError> {
    if operands.len() != 1 {
        return Err(GenerateError::UnsupportedPattern(
            "canonical brif replacement currently expects exactly one operand".to_string(),
        ));
    }
    if successors.len() != 2 {
        return Err(GenerateError::UnsupportedPattern(
            "canonical brif replacement currently expects exactly two successors".to_string(),
        ));
    }
    let cond = replacement_expr(&operands[0]);
    writeln!(out, "        let successors = if canonical_match.invert {{").unwrap();
    writeln!(
        out,
        "            vec![{}, {}]",
        successors[1], successors[0]
    )
    .unwrap();
    writeln!(out, "        }} else {{").unwrap();
    writeln!(
        out,
        "            vec![{}, {}]",
        successors[0], successors[1]
    )
    .unwrap();
    writeln!(out, "        }};").unwrap();
    writeln!(out, "        let replacement = ReplacementTerminator {{").unwrap();
    writeln!(out, "            opcode: TerminatorOpcode::BrIf,").unwrap();
    writeln!(out, "            operands: vec![{cond}],").unwrap();
    writeln!(out, "            successors,").unwrap();
    writeln!(out, "        }};").unwrap();
    Ok(())
}

/// Emit a replacement terminator payload for a matched root.
///
/// # Errors
///
/// Returns an error if the replacement shape is unsupported.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn emit_terminator_replacement(
    out: &mut String,
    kind: TerminatorKind,
    operands: &[Replacement],
    successors: &[usize],
) -> Result<(), GenerateError> {
    match kind {
        TerminatorKind::BrIf => {
            if operands.len() != 1 {
                return Err(GenerateError::UnsupportedPattern(
                    "brif replacement currently expects exactly one operand".to_string(),
                ));
            }
            let cond = replacement_expr(&operands[0]);
            writeln!(out, "        Some(ReplacementTerminator {{").unwrap();
            writeln!(out, "            opcode: TerminatorOpcode::BrIf,").unwrap();
            writeln!(out, "            operands: vec![{cond}],").unwrap();
            writeln!(
                out,
                "            successors: vec![{}],",
                successors
                    .iter()
                    .map(|idx| idx.to_string())
                    .collect::<Vec<_>>()
                    .join(", ")
            )
            .unwrap();
            writeln!(out, "        }})").unwrap();
        }
    }
    Ok(())
}

/// Render a terminator replacement operand expression.
///
/// # Panics
///
/// Panics if called with a replacement kind that is not legal for terminators.
fn replacement_expr(replacement: &Replacement) -> String {
    match replacement {
        Replacement::Binding { name } => format!("bind_{name}?"),
        Replacement::BoolConst { .. } | Replacement::BoolNot { .. } => {
            unreachable!("terminator replacements only support direct bindings")
        }
    }
}

/// Emit runtime checks for every side condition on a rule.
///
/// # Errors
///
/// Returns an error if a side condition uses an unsupported schema feature.
///
/// # Panics
///
/// Panics if writing to the in-memory output buffer fails unexpectedly.
fn emit_side_condition_checks(
    out: &mut String,
    side_conditions: &[SideCondition],
) -> Result<(), GenerateError> {
    for condition in side_conditions {
        let expr = side_condition_expr(condition)?;
        writeln!(out, "        if !({expr}) {{ return None; }}").unwrap();
    }
    Ok(())
}

/// Render the runtime boolean expression for one side condition.
///
/// # Errors
///
/// Returns an error if the condition uses an unsupported schema feature.
fn side_condition_expr(condition: &SideCondition) -> Result<String, GenerateError> {
    match condition {
        SideCondition::IntPredicate { binding, predicate } => {
            let expr = match predicate {
                IntPredicate::Zero => format!(
                    "matches!(bound_int_constant(func, bind_{binding}?), Some(value) if value == &{})",
                    bigint_expr("0")?
                ),
                IntPredicate::One => format!(
                    "matches!(bound_int_constant(func, bind_{binding}?), Some(value) if value == &{})",
                    bigint_expr("1")?
                ),
                IntPredicate::Odd => {
                    format!(
                        "matches!(bound_int_constant(func, bind_{binding}?), Some(value) if bigint_is_odd(value))"
                    )
                }
            };
            Ok(expr)
        }
        SideCondition::BestIntAnnotation {
            binding,
            annotation,
        } => Ok(format!(
            "best_int_annotation_matches(func, fact_cache, bind_{binding}?, &{})",
            int_annotation_expr(*annotation)
        )),
        SideCondition::KnownOne { binding, bit } => Ok(format!(
            "known_one(func, fact_cache, bind_{binding}?, {bit})"
        )),
        SideCondition::AllOf { conditions } => combine_side_conditions(conditions, "&&"),
        SideCondition::AnyOf { conditions } => combine_side_conditions(conditions, "||"),
        SideCondition::Not { condition } => Ok(format!("!({})", side_condition_expr(condition)?)),
    }
}

/// Combine multiple rendered side conditions with a boolean operator.
///
/// # Errors
///
/// Returns an error if any nested side condition cannot be rendered.
fn combine_side_conditions(
    conditions: &[SideCondition],
    op: &str,
) -> Result<String, GenerateError> {
    let exprs = conditions
        .iter()
        .map(side_condition_expr)
        .collect::<Result<Vec<_>, _>>()?;
    let fallback = if op == "&&" { "true" } else { "false" };
    if exprs.is_empty() {
        Ok(fallback.to_string())
    } else {
        Ok(format!("({})", exprs.join(&format!(" {op} "))))
    }
}

/// Stateful emitter for nested value-pattern matching code.
struct PatternGen {
    /// Counter used to mint fresh local variable names.
    next_local: usize,
    /// Current indentation depth in four-space units.
    indent: usize,
}

impl PatternGen {
    /// Create a fresh pattern emitter with the requested indentation depth.
    fn new(indent: usize) -> Self {
        Self {
            next_local: 0,
            indent,
        }
    }

    /// Emit code that matches one value pattern against a runtime value.
    ///
    /// # Errors
    ///
    /// Returns an error if the pattern uses an unsupported schema feature.
    fn emit_pattern(
        &mut self,
        out: &mut String,
        pattern: &Pattern,
        value_expr: &str,
    ) -> Result<(), GenerateError> {
        match pattern {
            Pattern::Capture { name, ty } => {
                if let Some(ty) = ty {
                    let expected = match ty {
                        ValueType::Int => "Type::Int",
                        ValueType::Bool => "Type::Bool",
                    };
                    self.line(
                        out,
                        &format!(
                            "if !matches!(func.value_type({value_expr}), Some({expected})) {{ return None; }}"
                        ),
                    );
                }
                self.line(
                    out,
                    &format!(
                        "if !bind_value_slot(&mut bind_{name}, {value_expr}) {{ return None; }}"
                    ),
                );
                self.emit_track_primary_inst(out, value_expr);
            }
            Pattern::Bind { name, pattern } => {
                self.line(
                    out,
                    &format!(
                        "if !bind_value_slot(&mut bind_{name}, {value_expr}) {{ return None; }}"
                    ),
                );
                self.emit_track_primary_inst(out, value_expr);
                self.emit_pattern(out, pattern, value_expr)?;
            }
            Pattern::IntConst { value } => {
                let inst_idx = self.local("const_inst_idx");
                let node = self.local("const_node");
                self.line(
                    out,
                    &format!(
                        "let Some({inst_idx}) = primary_inst_index({value_expr}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!(
                        "let Some({node}) = func.inst_pool.get({inst_idx}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!("if {node}.parent_block != root_block {{ return None; }};"),
                );
                self.line(out, &format!("match &{node}.inst.op {{"));
                self.indent += 1;
                self.line(
                    out,
                    &format!(
                        "Op::Const(actual) if actual == &{} => {{}}",
                        bigint_expr(value)?
                    ),
                );
                self.line(out, "_ => return None,");
                self.indent -= 1;
                self.line(out, "};");
                self.line(out, &format!("matched_insts.insert({inst_idx});"));
            }
            Pattern::IntConstBinding { name } => {
                let inst_idx = self.local("const_inst_idx");
                let node = self.local("const_node");
                self.line(
                    out,
                    &format!(
                        "let Some({inst_idx}) = primary_inst_index({value_expr}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!(
                        "let Some({node}) = func.inst_pool.get({inst_idx}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!("if {node}.parent_block != root_block {{ return None; }};"),
                );
                self.line(
                    out,
                    &format!("if !matches!(&{node}.inst.op, Op::Const(_)) {{ return None; }};"),
                );
                self.line(
                    out,
                    &format!(
                        "if !bind_value_slot(&mut bind_{name}, {value_expr}) {{ return None; }}"
                    ),
                );
                self.line(out, &format!("matched_insts.insert({inst_idx});"));
            }
            Pattern::Inst { op, attrs, args } => {
                let inst_idx = self.local("inst_idx");
                let node = self.local("node");
                self.line(
                    out,
                    &format!(
                        "let Some({inst_idx}) = primary_inst_index({value_expr}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!(
                        "let Some({node}) = func.inst_pool.get({inst_idx}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!("if {node}.parent_block != root_block {{ return None; }};"),
                );
                self.line(out, &format!("matched_insts.insert({inst_idx});"));
                self.emit_inst_match(out, op, attrs, args, &node)?;
            }
        }
        Ok(())
    }

    /// Emit the instruction-specific portion of a nested pattern match.
    ///
    /// # Errors
    ///
    /// Returns an error if the opcode or attributes are unsupported.
    fn emit_inst_match(
        &mut self,
        out: &mut String,
        op: &str,
        attrs: &[PatternAttr],
        args: &[Pattern],
        node: &str,
    ) -> Result<(), GenerateError> {
        let op_kind = classify_pattern_inst(op, attrs)?;
        let arm = match op_kind {
            PatternInstKind::Select => "Op::Select(cond, t, e)",
            PatternInstKind::And => "Op::And(a, b)",
            PatternInstKind::Xor => "Op::Xor(a, b)",
            PatternInstKind::ICmpEq => "Op::ICmp(ICmpOp::Eq, a, b)",
        };
        self.line(out, &format!("match &{node}.inst.op {{"));
        self.indent += 1;
        self.line(out, &format!("{arm} => {{"));
        self.indent += 1;

        let operand_exprs: Vec<String> = match op_kind {
            PatternInstKind::Select => vec![
                "cond.clone().raw().value".to_string(),
                "t.value".to_string(),
                "e.value".to_string(),
            ],
            PatternInstKind::And | PatternInstKind::Xor | PatternInstKind::ICmpEq => vec![
                "a.clone().raw().value".to_string(),
                "b.clone().raw().value".to_string(),
            ],
        };

        let arg_locals: Vec<String> = operand_exprs
            .iter()
            .map(|expr| {
                let local = self.local("arg");
                self.line(out, &format!("let {local} = {expr};"));
                local
            })
            .collect();

        if op_kind.is_commutative() && arg_locals.len() == 2 {
            let binding_names = collect_binding_names(args);
            let snapshot_bindings = self.local("snapshot_bindings");
            let snapshot_insts = self.local("snapshot_insts");
            let order_ok = self.local("order_ok");

            self.line(
                out,
                &format!(
                    "let {snapshot_bindings} = {};",
                    snapshot_tuple_expr(&binding_names)
                ),
            );
            self.line(
                out,
                &format!("let {snapshot_insts} = matched_insts.clone();"),
            );
            self.line(out, &format!("let {order_ok} = (|| -> Option<()> {{"));
            self.indent += 1;
            self.emit_pattern(out, &args[0], &arg_locals[0])?;
            self.emit_pattern(out, &args[1], &arg_locals[1])?;
            self.line(out, "Some(())");
            self.indent -= 1;
            self.line(out, "})();");
            self.line(out, &format!("if {order_ok}.is_none() {{"));
            self.indent += 1;
            if binding_names.is_empty() {
                self.line(out, &format!("let () = {snapshot_bindings};"));
            } else if binding_names.len() == 1 {
                self.line(
                    out,
                    &format!("bind_{} = {snapshot_bindings};", binding_names[0]),
                );
            } else {
                self.line(
                    out,
                    &format!(
                        "({}) = {snapshot_bindings};",
                        restore_tuple_targets(&binding_names)
                    ),
                );
            }
            self.line(out, &format!("matched_insts = {snapshot_insts};"));
            self.line(out, "(|| -> Option<()> {");
            self.indent += 1;
            self.emit_pattern(out, &args[0], &arg_locals[1])?;
            self.emit_pattern(out, &args[1], &arg_locals[0])?;
            self.line(out, "Some(())");
            self.indent -= 1;
            self.line(out, "})()?;");
            self.indent -= 1;
            self.line(out, "}");
        } else {
            for (arg, local) in args.iter().zip(arg_locals.iter()) {
                self.emit_pattern(out, arg, local)?;
            }
        }

        self.indent -= 1;
        self.line(out, "}");
        self.line(out, "_ => return None,");
        self.indent -= 1;
        self.line(out, "};");
        Ok(())
    }

    /// Allocate a fresh local variable name with the given prefix.
    fn local(&mut self, prefix: &str) -> String {
        let local = format!("{prefix}_{}", self.next_local);
        self.next_local += 1;
        local
    }

    /// Track a matched primary-result instruction when it stays in the root block.
    fn emit_track_primary_inst(&mut self, out: &mut String, value_expr: &str) {
        let inst_idx = self.local("captured_inst_idx");
        let node = self.local("captured_node");
        self.line(
            out,
            &format!("if let Some({inst_idx}) = primary_inst_index({value_expr}) {{"),
        );
        self.indent += 1;
        self.line(
            out,
            &format!("let Some({node}) = func.inst_pool.get({inst_idx}) else {{ return None; }};"),
        );
        self.line(
            out,
            &format!(
                "if {node}.parent_block == root_block {{ matched_insts.insert({inst_idx}); }}"
            ),
        );
        self.indent -= 1;
        self.line(out, "}");
    }

    /// Write one indented line to the generated output buffer.
    fn line(&self, out: &mut String, text: &str) {
        for _ in 0..self.indent {
            out.push_str("    ");
        }
        out.push_str(text);
        out.push('\n');
    }
}

/// Classified pattern instruction forms supported by the matcher generator.
#[derive(Clone, Copy)]
enum PatternInstKind {
    /// A `select` instruction.
    Select,
    /// A bitwise `and` instruction.
    And,
    /// A bitwise `xor` instruction.
    Xor,
    /// An equality `icmp`.
    ICmpEq,
}

impl PatternInstKind {
    /// Return whether operand order may be swapped during matching.
    fn is_commutative(self) -> bool {
        matches!(self, Self::And | Self::Xor | Self::ICmpEq)
    }
}

/// Terminator kinds supported by the generated rewrite runtime.
#[derive(Clone, Copy, PartialEq, Eq)]
enum TerminatorKind {
    /// A conditional branch with two successors.
    BrIf,
}

/// Classify a terminator root by opcode and successor count.
///
/// # Errors
///
/// Returns an error if the root is not a supported terminator shape.
fn classify_terminator_kind(
    op: &str,
    successor_count: usize,
) -> Result<TerminatorKind, GenerateError> {
    match op {
        "brif" if successor_count == 2 => Ok(TerminatorKind::BrIf),
        "brif" => Err(GenerateError::UnsupportedPattern(format!(
            "brif expects exactly 2 successors, got {successor_count}"
        ))),
        other => Err(GenerateError::UnsupportedPattern(format!(
            "unsupported terminator op `{other}`"
        ))),
    }
}

/// Classify an instruction pattern by opcode and attributes.
///
/// # Errors
///
/// Returns an error if the pattern is not supported by the generated matcher.
fn classify_pattern_inst(
    op: &str,
    attrs: &[PatternAttr],
) -> Result<PatternInstKind, GenerateError> {
    match op {
        "select" => Ok(PatternInstKind::Select),
        "and" => Ok(PatternInstKind::And),
        "xor" => Ok(PatternInstKind::Xor),
        "icmp" => match attrs {
            [PatternAttr::IcmpPred { value }] if value == "eq" => Ok(PatternInstKind::ICmpEq),
            [PatternAttr::IcmpPred { value }] => Err(GenerateError::UnsupportedPattern(format!(
                "icmp predicate `{value}`"
            ))),
            [] => Err(GenerateError::UnsupportedPattern(
                "icmp is missing required predicate attribute".to_string(),
            )),
            _ => Err(GenerateError::UnsupportedPattern(
                "icmp uses unsupported attribute set".to_string(),
            )),
        },
        other => Err(GenerateError::UnsupportedPattern(format!(
            "unsupported pattern op `{other}`"
        ))),
    }
}

/// Const-fold operations supported by the generated runtime.
#[derive(Clone, Copy)]
enum ConstFoldKind {
    /// `add`
    Add,
    /// `sub`
    Sub,
    /// `mul`
    Mul,
    /// `div`
    Div,
    /// `rem`
    Rem,
    /// `and`
    And,
    /// `or`
    Or,
    /// `xor`
    Xor,
    /// `band`
    BAnd,
    /// `bor`
    BOr,
    /// `bxor`
    BXor,
    /// `shl`
    Shl,
    /// `shr`
    Shr,
    /// `min`
    Min,
    /// `max`
    Max,
    /// `count_ones`
    CountOnes,
    /// `count_leading_zeros`
    CountLeadingZeros,
    /// `count_trailing_zeros`
    CountTrailingZeros,
    /// `bswap`
    Bswap,
    /// `bit_reverse`
    BitReverse,
    /// `rotate_left`
    RotateLeft,
    /// `rotate_right`
    RotateRight,
    /// `select`
    Select,
    /// `icmp eq`
    ICmpEq,
    /// `icmp ne`
    ICmpNe,
    /// `icmp lt`
    ICMPLt,
    /// `icmp le`
    ICmpLe,
    /// `icmp gt`
    ICmpGt,
    /// `icmp ge`
    ICmpGe,
}

/// Classify a const-fold root by opcode and attributes.
///
/// # Errors
///
/// Returns an error if the const-fold root is not supported by the runtime.
fn classify_const_fold(op: &str, attrs: &[PatternAttr]) -> Result<ConstFoldKind, GenerateError> {
    match op {
        "add" if attrs.is_empty() => Ok(ConstFoldKind::Add),
        "sub" if attrs.is_empty() => Ok(ConstFoldKind::Sub),
        "mul" if attrs.is_empty() => Ok(ConstFoldKind::Mul),
        "div" if attrs.is_empty() => Ok(ConstFoldKind::Div),
        "rem" if attrs.is_empty() => Ok(ConstFoldKind::Rem),
        "and" if attrs.is_empty() => Ok(ConstFoldKind::And),
        "or" if attrs.is_empty() => Ok(ConstFoldKind::Or),
        "xor" if attrs.is_empty() => Ok(ConstFoldKind::Xor),
        "band" if attrs.is_empty() => Ok(ConstFoldKind::BAnd),
        "bor" if attrs.is_empty() => Ok(ConstFoldKind::BOr),
        "bxor" if attrs.is_empty() => Ok(ConstFoldKind::BXor),
        "shl" if attrs.is_empty() => Ok(ConstFoldKind::Shl),
        "shr" if attrs.is_empty() => Ok(ConstFoldKind::Shr),
        "min" if attrs.is_empty() => Ok(ConstFoldKind::Min),
        "max" if attrs.is_empty() => Ok(ConstFoldKind::Max),
        "count_ones" if attrs.is_empty() => Ok(ConstFoldKind::CountOnes),
        "count_leading_zeros" if attrs.is_empty() => Ok(ConstFoldKind::CountLeadingZeros),
        "count_trailing_zeros" if attrs.is_empty() => Ok(ConstFoldKind::CountTrailingZeros),
        "bswap" if attrs.is_empty() => Ok(ConstFoldKind::Bswap),
        "bit_reverse" if attrs.is_empty() => Ok(ConstFoldKind::BitReverse),
        "rotate_left" if attrs.is_empty() => Ok(ConstFoldKind::RotateLeft),
        "rotate_right" if attrs.is_empty() => Ok(ConstFoldKind::RotateRight),
        "select" if attrs.is_empty() => Ok(ConstFoldKind::Select),
        "icmp" => match attrs {
            [PatternAttr::IcmpPred { value }] => match value.as_str() {
                "eq" => Ok(ConstFoldKind::ICmpEq),
                "ne" => Ok(ConstFoldKind::ICmpNe),
                "lt" => Ok(ConstFoldKind::ICMPLt),
                "le" => Ok(ConstFoldKind::ICmpLe),
                "gt" => Ok(ConstFoldKind::ICmpGt),
                "ge" => Ok(ConstFoldKind::ICmpGe),
                _ => Err(GenerateError::UnsupportedPattern(format!(
                    "unsupported const-fold icmp predicate `{value}`"
                ))),
            },
            _ => Err(GenerateError::UnsupportedPattern(
                "const-fold icmp uses unsupported attribute set".to_string(),
            )),
        },
        other => Err(GenerateError::UnsupportedPattern(format!(
            "unsupported const-fold op `{other}`"
        ))),
    }
}

/// Render the runtime enum expression for a const-fold kind.
fn const_fold_kind_expr(kind: ConstFoldKind) -> &'static str {
    match kind {
        ConstFoldKind::Add => "ConstFoldKind::Add",
        ConstFoldKind::Sub => "ConstFoldKind::Sub",
        ConstFoldKind::Mul => "ConstFoldKind::Mul",
        ConstFoldKind::Div => "ConstFoldKind::Div",
        ConstFoldKind::Rem => "ConstFoldKind::Rem",
        ConstFoldKind::And => "ConstFoldKind::And",
        ConstFoldKind::Or => "ConstFoldKind::Or",
        ConstFoldKind::Xor => "ConstFoldKind::Xor",
        ConstFoldKind::BAnd => "ConstFoldKind::BAnd",
        ConstFoldKind::BOr => "ConstFoldKind::BOr",
        ConstFoldKind::BXor => "ConstFoldKind::BXor",
        ConstFoldKind::Shl => "ConstFoldKind::Shl",
        ConstFoldKind::Shr => "ConstFoldKind::Shr",
        ConstFoldKind::Min => "ConstFoldKind::Min",
        ConstFoldKind::Max => "ConstFoldKind::Max",
        ConstFoldKind::CountOnes => "ConstFoldKind::CountOnes",
        ConstFoldKind::CountLeadingZeros => "ConstFoldKind::CountLeadingZeros",
        ConstFoldKind::CountTrailingZeros => "ConstFoldKind::CountTrailingZeros",
        ConstFoldKind::Bswap => "ConstFoldKind::Bswap",
        ConstFoldKind::BitReverse => "ConstFoldKind::BitReverse",
        ConstFoldKind::RotateLeft => "ConstFoldKind::RotateLeft",
        ConstFoldKind::RotateRight => "ConstFoldKind::RotateRight",
        ConstFoldKind::Select => "ConstFoldKind::Select",
        ConstFoldKind::ICmpEq => "ConstFoldKind::ICmp(ICmpOp::Eq)",
        ConstFoldKind::ICmpNe => "ConstFoldKind::ICmp(ICmpOp::Ne)",
        ConstFoldKind::ICMPLt => "ConstFoldKind::ICmp(ICmpOp::Lt)",
        ConstFoldKind::ICmpLe => "ConstFoldKind::ICmp(ICmpOp::Le)",
        ConstFoldKind::ICmpGt => "ConstFoldKind::ICmp(ICmpOp::Gt)",
        ConstFoldKind::ICmpGe => "ConstFoldKind::ICmp(ICmpOp::Ge)",
    }
}

/// Collect unique binding names referenced by a list of patterns.
fn collect_binding_names(patterns: &[Pattern]) -> Vec<&str> {
    let mut bindings = Vec::new();
    for pattern in patterns {
        pattern.collect_bindings(&mut bindings);
    }
    bindings
}

/// Render a tuple expression that snapshots the current binding slots.
fn snapshot_tuple_expr(binding_names: &[&str]) -> String {
    match binding_names {
        [] => "()".to_string(),
        [name] => format!("bind_{name}"),
        _ => format!(
            "({})",
            binding_names
                .iter()
                .map(|name| format!("bind_{name}"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

/// Render the tuple targets used to restore binding slots from a snapshot.
fn restore_tuple_targets(binding_names: &[&str]) -> String {
    binding_names
        .iter()
        .map(|name| format!("bind_{name}"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Render a Rust expression that reconstructs a decimal `BigInt`.
///
/// # Errors
///
/// Returns an error if `value` is not a valid decimal integer literal.
fn bigint_expr(value: &str) -> Result<String, GenerateError> {
    if let Ok(n) = value.parse::<u64>() {
        return Ok(format!("BigInt::from({n}u64)"));
    }

    if let Ok(n) = value.parse::<i64>() {
        return Ok(format!("BigInt::from({n}i64)"));
    }

    let _: BigInt = value
        .parse()
        .map_err(|_| GenerateError::InvalidIntConstant(value.to_string()))?;
    Ok(format!("parse_decimal_bigint({value:?})"))
}

/// Render the runtime `ValueRewrite` expression for a replacement.
///
/// # Errors
///
/// Returns an error if the replacement tree uses an unsupported value form.
fn value_rewrite_expr(replacement: &Replacement) -> Result<String, GenerateError> {
    match replacement {
        Replacement::Binding { name } => Ok(format!("ValueRewrite::Existing(bind_{name}?)")),
        Replacement::BoolConst { value } => Ok(format!("ValueRewrite::ConstBool({value})")),
        Replacement::BoolNot { value } => Ok(format!(
            "ValueRewrite::Expr(ReplacementExpr::BoolNot(Box::new({})))",
            replacement_expr_tree(value)?
        )),
    }
}

/// Render the runtime `ReplacementExpr` tree for a replacement.
///
/// # Errors
///
/// Returns an error if the replacement tree uses an unsupported value form.
fn replacement_expr_tree(replacement: &Replacement) -> Result<String, GenerateError> {
    match replacement {
        Replacement::Binding { name } => Ok(format!("ReplacementExpr::Value(bind_{name}?)")),
        Replacement::BoolConst { value } => Ok(format!("ReplacementExpr::ConstBool({value})")),
        Replacement::BoolNot { value } => Ok(format!(
            "ReplacementExpr::BoolNot(Box::new({}))",
            replacement_expr_tree(value)?
        )),
    }
}

/// Render an `IntAnnotation` construction expression.
fn int_annotation_expr(annotation: IntAnnotationSpec) -> String {
    let (bit_width, signedness) = match annotation {
        IntAnnotationSpec::Signed { bits } => (bits, "IntSignedness::Signed"),
        IntAnnotationSpec::Unsigned { bits } => (bits, "IntSignedness::Unsigned"),
        IntAnnotationSpec::DontCare { bits } => (bits, "IntSignedness::DontCare"),
    };
    format!("IntAnnotation {{ bit_width: {bit_width}, signedness: {signedness} }}")
}

/// Convert an arbitrary rule name into a Rust identifier fragment.
fn rule_ident(name: &str) -> String {
    let mut ident = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            ident.push(ch.to_ascii_lowercase());
        } else {
            ident.push('_');
        }
    }
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}
