use std::fmt::Write;

use num_bigint::BigInt;

use crate::GenerateError;
use crate::schema::{Pattern, PatternAttr, PeepholeRule, PeepholeSpec, Rewrite, ValueType};

pub fn generate(spec: &PeepholeSpec) -> Result<String, GenerateError> {
    let mut out = String::new();
    writeln!(out, "// @generated by tuffy_opt_gen -- DO NOT EDIT").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "pub(super) const GENERATED_RULE_COUNT: usize = {};",
        spec.rules.len()
    )
    .unwrap();
    writeln!(out).unwrap();

    for rule in &spec.rules {
        generate_rule_fn(&mut out, rule)?;
    }

    generate_dispatch(&mut out, &spec.rules);

    Ok(out)
}

fn generate_dispatch(out: &mut String, rules: &[PeepholeRule]) {
    writeln!(out, "#[allow(clippy::question_mark)]").unwrap();
    writeln!(
        out,
        "pub(super) fn try_apply_generated_rule(func: &mut Function, root_idx: u32, stats: &mut PeepholeStats) -> bool {{"
    )
    .unwrap();
    if rules.is_empty() {
        writeln!(out, "    let _ = (func, root_idx, stats);").unwrap();
        writeln!(out, "    false").unwrap();
    } else {
        for rule in rules {
            let ident = rule_ident(&rule.name);
            writeln!(
                out,
                "    if try_apply_{ident}(func, root_idx, stats) {{ return true; }}"
            )
            .unwrap();
        }
        writeln!(out, "    false").unwrap();
    }
    writeln!(out, "}}").unwrap();
}

fn generate_rule_fn(out: &mut String, rule: &PeepholeRule) -> Result<(), GenerateError> {
    let ident = rule_ident(&rule.name);
    let mut bindings = Vec::new();
    match &rule.rewrite {
        Rewrite::Value { root, .. } => root.collect_bindings(&mut bindings),
        Rewrite::Brif { condition, .. } => condition.collect_bindings(&mut bindings),
    }

    writeln!(
        out,
        "#[allow(clippy::question_mark, unused_parens, clippy::double_parens)]"
    )
    .unwrap();
    writeln!(
        out,
        "fn try_apply_{ident}(func: &mut Function, root_idx: u32, stats: &mut PeepholeStats) -> bool {{"
    )
    .unwrap();
    for binding in &bindings {
        writeln!(out, "    let mut bind_{binding}: Option<ValueRef> = None;").unwrap();
    }
    writeln!(out, "    let mut matched_insts = BTreeSet::new();").unwrap();
    writeln!(out, "    let replacement = (|| -> Option<ValueRef> {{").unwrap();
    writeln!(
        out,
        "        let Some(root_node) = func.inst_pool.get(root_idx) else {{ return None; }};"
    )
    .unwrap();
    writeln!(out, "        let root_block = root_node.parent_block;").unwrap();
    match &rule.rewrite {
        Rewrite::Value { root, replacement } => {
            writeln!(
                out,
                "        let root_value = ValueRef::inst_result(root_idx);"
            )
            .unwrap();
            let mut pattern_gen = PatternGen::new(2);
            pattern_gen.emit_pattern(out, root, "root_value")?;
            writeln!(
                out,
                "        let replacement = bind_{}?;",
                replacement.binding_name()
            )
            .unwrap();
            writeln!(out, "        Some(replacement)").unwrap();
        }
        Rewrite::Brif {
            condition,
            replacement,
            ..
        } => {
            writeln!(out, "        let root_cond = match &root_node.inst.op {{").unwrap();
            writeln!(
                out,
                "            Op::BrIf(cond, _, _, _, _) => cond.clone().raw().value,"
            )
            .unwrap();
            writeln!(out, "            _ => return None,").unwrap();
            writeln!(out, "        }};").unwrap();
            let mut pattern_gen = PatternGen::new(2);
            pattern_gen.emit_pattern(out, condition, "root_cond")?;
            writeln!(
                out,
                "        let replacement = bind_{}?;",
                replacement.binding_name()
            )
            .unwrap();
            writeln!(out, "        Some(replacement)").unwrap();
        }
    }
    writeln!(out, "    }})();").unwrap();
    writeln!(
        out,
        "    let Some(replacement) = replacement else {{ return false; }};"
    )
    .unwrap();
    match &rule.rewrite {
        Rewrite::Value { .. } => {
            writeln!(
                out,
                "    apply_value_rewrite(func, root_idx, replacement, &matched_insts);"
            )
            .unwrap();
        }
        Rewrite::Brif { invert, .. } => {
            writeln!(
                out,
                "    apply_brif_rewrite(func, root_idx, replacement, {invert}, &matched_insts);"
            )
            .unwrap();
        }
    }
    writeln!(out, "    stats.record({:?});", rule.name).unwrap();
    writeln!(out, "    true").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    Ok(())
}

struct PatternGen {
    next_local: usize,
    indent: usize,
}

impl PatternGen {
    fn new(indent: usize) -> Self {
        Self {
            next_local: 0,
            indent,
        }
    }

    fn emit_pattern(
        &mut self,
        out: &mut String,
        pattern: &Pattern,
        value_expr: &str,
    ) -> Result<(), GenerateError> {
        match pattern {
            Pattern::Capture { name, ty } => {
                if let Some(ty) = ty {
                    let expected = match ty {
                        ValueType::Int => "Type::Int",
                        ValueType::Bool => "Type::Bool",
                    };
                    self.line(
                        out,
                        &format!(
                            "if !matches!(func.value_type({value_expr}), Some({expected})) {{ return None; }}"
                        ),
                    );
                }
                self.line(
                    out,
                    &format!(
                        "if !bind_value_slot(&mut bind_{name}, {value_expr}) {{ return None; }}"
                    ),
                );
            }
            Pattern::Bind { name, pattern } => {
                self.line(
                    out,
                    &format!(
                        "if !bind_value_slot(&mut bind_{name}, {value_expr}) {{ return None; }}"
                    ),
                );
                self.emit_pattern(out, pattern, value_expr)?;
            }
            Pattern::IntConst { value } => {
                let inst_idx = self.local("const_inst_idx");
                let node = self.local("const_node");
                self.line(
                    out,
                    &format!(
                        "let Some({inst_idx}) = primary_inst_index({value_expr}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!(
                        "let Some({node}) = func.inst_pool.get({inst_idx}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!("if {node}.parent_block != root_block {{ return None; }};"),
                );
                self.line(out, &format!("match &{node}.inst.op {{"));
                self.indent += 1;
                self.line(
                    out,
                    &format!(
                        "Op::Const(actual) if actual == &{} => {{}}",
                        bigint_expr(value)?
                    ),
                );
                self.line(out, "_ => return None,");
                self.indent -= 1;
                self.line(out, "};");
                self.line(out, &format!("matched_insts.insert({inst_idx});"));
            }
            Pattern::IntConstBinding { name } => {
                let inst_idx = self.local("const_inst_idx");
                let node = self.local("const_node");
                self.line(
                    out,
                    &format!(
                        "let Some({inst_idx}) = primary_inst_index({value_expr}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!(
                        "let Some({node}) = func.inst_pool.get({inst_idx}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!("if {node}.parent_block != root_block {{ return None; }};"),
                );
                self.line(
                    out,
                    &format!("if !matches!(&{node}.inst.op, Op::Const(_)) {{ return None; }};"),
                );
                self.line(
                    out,
                    &format!(
                        "if !bind_value_slot(&mut bind_{name}, {value_expr}) {{ return None; }}"
                    ),
                );
                self.line(out, &format!("matched_insts.insert({inst_idx});"));
            }
            Pattern::Inst { op, attrs, args } => {
                let inst_idx = self.local("inst_idx");
                let node = self.local("node");
                self.line(
                    out,
                    &format!(
                        "let Some({inst_idx}) = primary_inst_index({value_expr}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!(
                        "let Some({node}) = func.inst_pool.get({inst_idx}) else {{ return None; }};"
                    ),
                );
                self.line(
                    out,
                    &format!("if {node}.parent_block != root_block {{ return None; }};"),
                );
                self.line(out, &format!("matched_insts.insert({inst_idx});"));
                self.emit_inst_match(out, op, attrs, args, &node)?;
            }
        }
        Ok(())
    }

    fn emit_inst_match(
        &mut self,
        out: &mut String,
        op: &str,
        attrs: &[PatternAttr],
        args: &[Pattern],
        node: &str,
    ) -> Result<(), GenerateError> {
        let op_kind = classify_pattern_inst(op, attrs)?;
        let arm = match op_kind {
            PatternInstKind::Select => "Op::Select(cond, t, e)",
            PatternInstKind::And => "Op::And(a, b)",
            PatternInstKind::Xor => "Op::Xor(a, b)",
            PatternInstKind::ICmpEq => "Op::ICmp(ICmpOp::Eq, a, b)",
        };
        self.line(out, &format!("match &{node}.inst.op {{"));
        self.indent += 1;
        self.line(out, &format!("{arm} => {{"));
        self.indent += 1;

        let operand_exprs: Vec<String> = match op_kind {
            PatternInstKind::Select => vec![
                "cond.clone().raw().value".to_string(),
                "t.value".to_string(),
                "e.value".to_string(),
            ],
            PatternInstKind::And | PatternInstKind::Xor | PatternInstKind::ICmpEq => vec![
                "a.clone().raw().value".to_string(),
                "b.clone().raw().value".to_string(),
            ],
        };

        let arg_locals: Vec<String> = operand_exprs
            .iter()
            .map(|expr| {
                let local = self.local("arg");
                self.line(out, &format!("let {local} = {expr};"));
                local
            })
            .collect();

        if op_kind.is_commutative() && arg_locals.len() == 2 {
            let binding_names = collect_binding_names(args);
            let snapshot_bindings = self.local("snapshot_bindings");
            let snapshot_insts = self.local("snapshot_insts");
            let order_ok = self.local("order_ok");

            self.line(
                out,
                &format!(
                    "let {snapshot_bindings} = {};",
                    snapshot_tuple_expr(&binding_names)
                ),
            );
            self.line(
                out,
                &format!("let {snapshot_insts} = matched_insts.clone();"),
            );
            self.line(out, &format!("let {order_ok} = (|| -> Option<()> {{"));
            self.indent += 1;
            self.emit_pattern(out, &args[0], &arg_locals[0])?;
            self.emit_pattern(out, &args[1], &arg_locals[1])?;
            self.line(out, "Some(())");
            self.indent -= 1;
            self.line(out, "})();");
            self.line(out, &format!("if {order_ok}.is_none() {{"));
            self.indent += 1;
            if binding_names.is_empty() {
                self.line(out, &format!("let () = {snapshot_bindings};"));
            } else if binding_names.len() == 1 {
                self.line(
                    out,
                    &format!("bind_{} = {snapshot_bindings};", binding_names[0]),
                );
            } else {
                self.line(
                    out,
                    &format!(
                        "({}) = {snapshot_bindings};",
                        restore_tuple_targets(&binding_names)
                    ),
                );
            }
            self.line(out, &format!("matched_insts = {snapshot_insts};"));
            self.line(out, "(|| -> Option<()> {");
            self.indent += 1;
            self.emit_pattern(out, &args[0], &arg_locals[1])?;
            self.emit_pattern(out, &args[1], &arg_locals[0])?;
            self.line(out, "Some(())");
            self.indent -= 1;
            self.line(out, "})()?;");
            self.indent -= 1;
            self.line(out, "}");
        } else {
            for (arg, local) in args.iter().zip(arg_locals.iter()) {
                self.emit_pattern(out, arg, local)?;
            }
        }

        self.indent -= 1;
        self.line(out, "}");
        self.line(out, "_ => return None,");
        self.indent -= 1;
        self.line(out, "};");
        Ok(())
    }

    fn local(&mut self, prefix: &str) -> String {
        let local = format!("{prefix}_{}", self.next_local);
        self.next_local += 1;
        local
    }

    fn line(&self, out: &mut String, text: &str) {
        for _ in 0..self.indent {
            out.push_str("    ");
        }
        out.push_str(text);
        out.push('\n');
    }
}

#[derive(Clone, Copy)]
enum PatternInstKind {
    Select,
    And,
    Xor,
    ICmpEq,
}

impl PatternInstKind {
    fn is_commutative(self) -> bool {
        matches!(self, Self::And | Self::Xor | Self::ICmpEq)
    }
}

fn classify_pattern_inst(
    op: &str,
    attrs: &[PatternAttr],
) -> Result<PatternInstKind, GenerateError> {
    match op {
        "select" => Ok(PatternInstKind::Select),
        "and" => Ok(PatternInstKind::And),
        "xor" => Ok(PatternInstKind::Xor),
        "icmp" => match attrs {
            [PatternAttr::IcmpPred { value }] if value == "eq" => Ok(PatternInstKind::ICmpEq),
            [PatternAttr::IcmpPred { value }] => Err(GenerateError::UnsupportedPattern(format!(
                "icmp predicate `{value}`"
            ))),
            [] => Err(GenerateError::UnsupportedPattern(
                "icmp is missing required predicate attribute".to_string(),
            )),
            _ => Err(GenerateError::UnsupportedPattern(
                "icmp uses unsupported attribute set".to_string(),
            )),
        },
        other => Err(GenerateError::UnsupportedPattern(format!(
            "unsupported pattern op `{other}`"
        ))),
    }
}

fn collect_binding_names(patterns: &[Pattern]) -> Vec<&str> {
    let mut bindings = Vec::new();
    for pattern in patterns {
        pattern.collect_bindings(&mut bindings);
    }
    bindings
}

fn snapshot_tuple_expr(binding_names: &[&str]) -> String {
    match binding_names {
        [] => "()".to_string(),
        [name] => format!("bind_{name}"),
        _ => format!(
            "({})",
            binding_names
                .iter()
                .map(|name| format!("bind_{name}"))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn restore_tuple_targets(binding_names: &[&str]) -> String {
    binding_names
        .iter()
        .map(|name| format!("bind_{name}"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn bigint_expr(value: &str) -> Result<String, GenerateError> {
    if let Ok(n) = value.parse::<u64>() {
        return Ok(format!("BigInt::from({n}u64)"));
    }

    if let Ok(n) = value.parse::<i64>() {
        return Ok(format!("BigInt::from({n}i64)"));
    }

    let _: BigInt = value
        .parse()
        .map_err(|_| GenerateError::InvalidIntConstant(value.to_string()))?;
    Ok(format!("parse_decimal_bigint({value:?})"))
}

fn rule_ident(name: &str) -> String {
    let mut ident = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            ident.push(ch.to_ascii_lowercase());
        } else {
            ident.push('_');
        }
    }
    if ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident.insert(0, '_');
    }
    ident
}
