use std::fmt::Write;

use crate::GenerateError;
use crate::facts_schema::{
    FactResult, FactSpec, InstFactRule, IntAnnotationBackwardKind, IntAnnotationForwardKind,
    KnownBitsBackwardKind, KnownBitsForwardKind, ResultFactRule,
};

pub fn generate(spec: &FactSpec) -> Result<String, GenerateError> {
    let mut out = String::new();
    writeln!(out, "// @generated by tuffy_opt_gen -- DO NOT EDIT").unwrap();
    writeln!(out).unwrap();
    generate_forward(&mut out, spec)?;
    writeln!(out).unwrap();
    generate_backward(&mut out, spec)?;
    Ok(out)
}

fn generate_forward(out: &mut String, spec: &FactSpec) -> Result<(), GenerateError> {
    writeln!(
        out,
        "fn generated_forward_int_facts(func: &Function, value: ValueRef, current: &BTreeMap<u32, IntFacts>) -> Option<IntFacts> {{"
    )
    .unwrap();
    writeln!(out, "    if value.is_block_arg() {{ return None; }}").unwrap();
    writeln!(
        out,
        "    let idx = if value.is_secondary_result() {{ value.inst_index() }} else {{ value.index() }};"
    )
    .unwrap();
    writeln!(out, "    let node = func.inst_pool.get(idx)?;").unwrap();
    writeln!(out, "    if value.is_secondary_result() {{").unwrap();
    writeln!(out, "        let facts = match &node.inst.op {{").unwrap();
    for rule in spec
        .result_rules
        .iter()
        .filter(|rule| rule.result == FactResult::Secondary)
    {
        emit_forward_arm(out, rule)?;
    }
    writeln!(out, "            _ => forward_unknown(),").unwrap();
    writeln!(out, "        }};").unwrap();
    writeln!(out, "        return Some(facts);").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    let facts = match &node.inst.op {{").unwrap();
    for rule in spec
        .result_rules
        .iter()
        .filter(|rule| rule.result == FactResult::Primary)
    {
        emit_forward_arm(out, rule)?;
    }
    writeln!(out, "        _ => forward_unknown(),").unwrap();
    writeln!(out, "    }};").unwrap();
    writeln!(out, "    Some(facts)").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn emit_forward_arm(out: &mut String, rule: &ResultFactRule) -> Result<(), GenerateError> {
    let helper = forward_helper_name(rule)?;
    let line = match rule.op.as_str() {
        "const" => format!(
            "        // {}\n        Op::Const(value) => {helper}(value),",
            rule.proof_ref
        ),
        "select" => format!(
            "        // {}\n        Op::Select(_, true_value, false_value) => {helper}(func, current, true_value, false_value),",
            rule.proof_ref
        ),
        "and" => format!(
            "        // {}\n        Op::And(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "or" => format!(
            "        // {}\n        Op::Or(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "xor" => format!(
            "        // {}\n        Op::Xor(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "shl" => format!(
            "        // {}\n        Op::Shl(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "shr" => format!(
            "        // {}\n        Op::Shr(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw()),",
            rule.proof_ref
        ),
        "merge" => format!(
            "        // {}\n        Op::Merge(lhs, rhs, width) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw(), *width),",
            rule.proof_ref
        ),
        "split" => match rule.result {
            FactResult::Primary => format!(
                "        // {}\n        Op::Split(src, width) => {helper}(func, current, &src.clone().raw(), *width),",
                rule.proof_ref
            ),
            FactResult::Secondary => format!(
                "        // {}\n        Op::Split(src, width) => {helper}(func, current, &src.clone().raw(), *width),",
                rule.proof_ref
            ),
        },
        other => {
            return Err(GenerateError::UnsupportedFactsRule(format!(
                "unsupported forward fact op `{other}`"
            )));
        }
    };
    writeln!(out, "{line}").unwrap();
    Ok(())
}

fn forward_helper_name(rule: &ResultFactRule) -> Result<&'static str, GenerateError> {
    match (rule.known_bits_forward, rule.int_annotation_forward) {
        (KnownBitsForwardKind::Unknown, IntAnnotationForwardKind::Unknown) => Ok("forward_unknown"),
        (KnownBitsForwardKind::Const, IntAnnotationForwardKind::Const) => Ok("forward_const"),
        (KnownBitsForwardKind::Select, IntAnnotationForwardKind::Select) => Ok("forward_select"),
        (KnownBitsForwardKind::BitAnd, IntAnnotationForwardKind::BitAnd) => Ok("forward_bitand"),
        (KnownBitsForwardKind::BitOr, IntAnnotationForwardKind::BitOr) => Ok("forward_bitor"),
        (KnownBitsForwardKind::BitXor, IntAnnotationForwardKind::BitXor) => Ok("forward_bitxor"),
        (KnownBitsForwardKind::Shl, IntAnnotationForwardKind::Unknown) => Ok("forward_shl"),
        (KnownBitsForwardKind::Shr, IntAnnotationForwardKind::Unknown) => Ok("forward_shr"),
        (KnownBitsForwardKind::Merge, IntAnnotationForwardKind::Unknown) => Ok("forward_merge"),
        (KnownBitsForwardKind::SplitHi, IntAnnotationForwardKind::Unknown) => {
            Ok("forward_split_hi")
        }
        (KnownBitsForwardKind::SplitLo, IntAnnotationForwardKind::SplitLo) => {
            Ok("forward_split_lo")
        }
        other => Err(GenerateError::UnsupportedFactsRule(format!(
            "unsupported forward fact kind combination: {other:?}"
        ))),
    }
}

fn generate_backward(out: &mut String, spec: &FactSpec) -> Result<(), GenerateError> {
    writeln!(
        out,
        "fn generated_backward_int_facts(func: &Function, inst_idx: u32, primary_result: &IntFacts, secondary_result: Option<&IntFacts>, current: &BTreeMap<u32, IntFacts>) -> Vec<BackwardFactUpdate> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    let Some(node) = func.inst_pool.get(inst_idx) else {{ return Vec::new(); }};"
    )
    .unwrap();
    writeln!(out, "    let fallback_secondary = IntFacts::unknown();").unwrap();
    writeln!(
        out,
        "    let secondary_result = secondary_result.unwrap_or(&fallback_secondary);"
    )
    .unwrap();
    writeln!(out, "    match &node.inst.op {{").unwrap();
    for rule in &spec.inst_rules {
        emit_backward_arm(out, rule)?;
    }
    writeln!(out, "        _ => Vec::new(),").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn emit_backward_arm(out: &mut String, rule: &InstFactRule) -> Result<(), GenerateError> {
    let helper = backward_helper_name(rule)?;
    let line = match rule.op.as_str() {
        "select" => format!(
            "        // {}\n        Op::Select(_, true_value, false_value) => {helper}(true_value, false_value, primary_result),",
            rule.proof_ref
        ),
        "and" => format!(
            "        // {}\n        Op::And(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw(), primary_result),",
            rule.proof_ref
        ),
        "or" => format!(
            "        // {}\n        Op::Or(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw(), primary_result),",
            rule.proof_ref
        ),
        "xor" => format!(
            "        // {}\n        Op::Xor(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw(), primary_result),",
            rule.proof_ref
        ),
        "shl" => format!(
            "        // {}\n        Op::Shl(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw(), primary_result),",
            rule.proof_ref
        ),
        "shr" => format!(
            "        // {}\n        Op::Shr(lhs, rhs) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw(), primary_result),",
            rule.proof_ref
        ),
        "merge" => format!(
            "        // {}\n        Op::Merge(lhs, rhs, width) => {helper}(func, current, &lhs.clone().raw(), &rhs.clone().raw(), *width, primary_result),",
            rule.proof_ref
        ),
        "split" => format!(
            "        // {}\n        Op::Split(src, width) => {helper}(func, current, &src.clone().raw(), *width, primary_result, secondary_result),",
            rule.proof_ref
        ),
        other => {
            return Err(GenerateError::UnsupportedFactsRule(format!(
                "unsupported backward fact op `{other}`"
            )));
        }
    };
    writeln!(out, "{line}").unwrap();
    Ok(())
}

fn backward_helper_name(rule: &InstFactRule) -> Result<&'static str, GenerateError> {
    match (rule.known_bits_backward, rule.int_annotation_backward) {
        (KnownBitsBackwardKind::None, IntAnnotationBackwardKind::None) => Ok("backward_none"),
        (KnownBitsBackwardKind::Select, IntAnnotationBackwardKind::Select) => Ok("backward_select"),
        (KnownBitsBackwardKind::BitAnd, IntAnnotationBackwardKind::None) => Ok("backward_bitand"),
        (KnownBitsBackwardKind::BitOr, IntAnnotationBackwardKind::None) => Ok("backward_bitor"),
        (KnownBitsBackwardKind::BitXor, IntAnnotationBackwardKind::None) => Ok("backward_bitxor"),
        (KnownBitsBackwardKind::Shl, IntAnnotationBackwardKind::None) => Ok("backward_shl"),
        (KnownBitsBackwardKind::Shr, IntAnnotationBackwardKind::None) => Ok("backward_shr"),
        (KnownBitsBackwardKind::Merge, IntAnnotationBackwardKind::None) => Ok("backward_merge"),
        (KnownBitsBackwardKind::Split, IntAnnotationBackwardKind::Split) => Ok("backward_split"),
        other => Err(GenerateError::UnsupportedFactsRule(format!(
            "unsupported backward fact kind combination: {other:?}"
        ))),
    }
}
