use std::fmt::Write;

use crate::GenerateError;
use crate::pass_manifest_schema::{CleanupPassVerification, OptPassFamily, OptPassManifestSpec};

pub fn generate(spec: &OptPassManifestSpec) -> Result<String, GenerateError> {
    let mut out = String::new();
    let local_count = spec.local_families.len();
    let module_count = spec.module_families.len();
    let verified_count = spec
        .local_families
        .iter()
        .chain(spec.module_families.iter())
        .filter(|family| family.verification == CleanupPassVerification::Verified)
        .count();
    let legacy_count = local_count + module_count - verified_count;

    writeln!(out, "// @generated by tuffy_opt_gen -- DO NOT EDIT").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "pub(crate) const GENERATED_LOCAL_CLEANUP_PASS_COUNT: usize = {local_count};"
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const GENERATED_MODULE_CLEANUP_PASS_COUNT: usize = {module_count};"
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const GENERATED_VERIFIED_CLEANUP_PASS_COUNT: usize = {verified_count};"
    )
    .unwrap();
    writeln!(
        out,
        "pub(crate) const GENERATED_LEGACY_CLEANUP_PASS_COUNT: usize = {legacy_count};"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "#[derive(Clone, Copy, Debug, PartialEq, Eq)]").unwrap();
    writeln!(out, "pub(crate) enum CleanupPassVerification {{").unwrap();
    writeln!(out, "    Verified,").unwrap();
    writeln!(out, "    Legacy,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(out, "#[derive(Clone, Copy, Debug)]").unwrap();
    writeln!(out, "pub(crate) struct CleanupPassFamilyDescriptor {{").unwrap();
    writeln!(out, "    pub(crate) name: &'static str,").unwrap();
    writeln!(out, "    pub(crate) runner: &'static str,").unwrap();
    writeln!(out, "    pub(crate) verification: CleanupPassVerification,").unwrap();
    writeln!(out, "    pub(crate) lean_source: Option<&'static str>,").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    generate_descriptor_array(
        &mut out,
        "GENERATED_LOCAL_CLEANUP_FAMILIES",
        &spec.local_families,
    );
    writeln!(out).unwrap();
    generate_descriptor_array(
        &mut out,
        "GENERATED_MODULE_CLEANUP_FAMILIES",
        &spec.module_families,
    );
    writeln!(out).unwrap();
    generate_local_dispatch(&mut out, &spec.local_families)?;
    writeln!(out).unwrap();
    generate_module_dispatch(&mut out, &spec.module_families)?;
    Ok(out)
}

fn generate_descriptor_array(out: &mut String, name: &str, families: &[OptPassFamily]) {
    writeln!(out, "#[allow(dead_code)]").unwrap();
    writeln!(
        out,
        "pub(crate) const {name}: &[CleanupPassFamilyDescriptor] = &["
    )
    .unwrap();
    for family in families {
        let verification = match family.verification {
            CleanupPassVerification::Verified => "CleanupPassVerification::Verified",
            CleanupPassVerification::Legacy => "CleanupPassVerification::Legacy",
        };
        let lean_source = match &family.lean_source {
            Some(source) => format!("Some({source:?})"),
            None => "None".to_string(),
        };
        writeln!(
            out,
            "    CleanupPassFamilyDescriptor {{ name: {:?}, runner: {:?}, verification: {verification}, lean_source: {lean_source} }},",
            family.name, family.runner
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

fn generate_local_dispatch(
    out: &mut String,
    families: &[OptPassFamily],
) -> Result<(), GenerateError> {
    writeln!(
        out,
        "pub(crate) fn run_generated_local_cleanup_passes(func: &mut Function) -> PeepholeStats {{"
    )
    .unwrap();
    writeln!(out, "    let mut total = PeepholeStats::default();").unwrap();
    for family in families {
        writeln!(
            out,
            "    total.merge({});",
            local_runner_expr(&family.runner)?
        )
        .unwrap();
    }
    writeln!(out, "    total").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn generate_module_dispatch(
    out: &mut String,
    families: &[OptPassFamily],
) -> Result<(), GenerateError> {
    writeln!(
        out,
        "pub(crate) fn run_generated_module_cleanup_passes(module: &mut Module, changed_functions: Option<&[bool]>) -> PeepholeStats {{"
    )
    .unwrap();
    writeln!(out, "    let mut total = PeepholeStats::default();").unwrap();
    for family in families {
        writeln!(
            out,
            "    total.merge({});",
            module_runner_expr(&family.runner)?
        )
        .unwrap();
    }
    writeln!(out, "    total").unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

fn local_runner_expr(runner: &str) -> Result<&'static str, GenerateError> {
    match runner {
        "promote" => Ok("crate::promote::promote_function(func)"),
        "peephole" => Ok("crate::peephole::optimize_function(func)"),
        "range" => Ok("crate::range::optimize_function(func)"),
        "cfg_cleanup" => Ok("crate::cfg_cleanup::optimize_function(func)"),
        _ => Err(GenerateError::UnsupportedPassFamilyRunner(
            runner.to_string(),
        )),
    }
}

fn module_runner_expr(runner: &str) -> Result<&'static str, GenerateError> {
    match runner {
        "bulk_memory" => Ok("crate::bulk_memory::optimize_module(module, changed_functions)"),
        "scalar_swap" => Ok("crate::scalar_swap::optimize_module(module, changed_functions)"),
        _ => Err(GenerateError::UnsupportedPassFamilyRunner(
            runner.to_string(),
        )),
    }
}
